import { InventoryItem } from '../types';
  
export const LAB_REGISTRY: Partial<InventoryItem>[] = [
  { id: 1000, name: "Lipid Panel", price: 950.0, type: "Test", category: "LABORATORY" },
  { id: 1001, name: "HbA1c", price: 650.0, type: "Test", category: "LABORATORY" },
  { id: 1002, name: "AFB Stain", price: 300.0, type: "Service", category: "LABORATORY" },
  { id: 1003, name: "Culture + Sensitivity", price: 600.0, type: "Service", category: "LABORATORY" },
  { id: 1004, name: "Culture Blood +Sensitivity", price: 850.0, type: "Service", category: "LABORATORY" },
  { id: 1005, name: "Gram Stain", price: 300.0, type: "Service", category: "LABORATORY" },
  { id: 1006, name: "Leprosy AFB", price: 300.0, type: "Service", category: "LABORATORY" },
  { id: 1007, name: "Skin Scraping KOH", price: 300.0, type: "Service", category: "LABORATORY" },
  { id: 1008, name: "Wet smear", price: 300.0, type: "Service", category: "LABORATORY" },
  { id: 1009, name: "Water Culture", price: 400.0, type: "Service", category: "LABORATORY" },
  { id: 1010, name: "ADA MTB", price: 1300.0, type: "Service", category: "LABORATORY" },
  { id: 1011, name: "GENEXPERT MTB/RIF", price: 4300.0, type: "Service", category: "LABORATORY" },
  { id: 1012, name: "Peritoneal Fluid Package", price: 600.0, type: "Service", category: "LABORATORY" },
  { id: 1013, name: "Pleural Fluid Package", price: 600.0, type: "Service", category: "LABORATORY" },
  { id: 1014, name: "Semen Analysis Package", price: 600.0, type: "Service", category: "LABORATORY" },
  { id: 1015, name: "Spinal Fluid (CSF) Package", price: 600.0, type: "Service", category: "LABORATORY" },
  { id: 1016, name: "Synovial Fluid Package", price: 600.0, type: "Service", category: "LABORATORY" },
  { id: 1017, name: "K+, NA+, CL", price: 600.0, type: "Service", category: "LABORATORY" },
  { id: 1018, name: "Albumin", price: 340.0, type: "Service", category: "LABORATORY" },
  { id: 1019, name: "Alk Phos", price: 340.0, type: "Service", category: "LABORATORY" },
  { id: 1020, name: "ALT (Old term SGPT)", price: 340.0, type: "Service", category: "LABORATORY" },
  { id: 1021, name: "Amylase", price: 500.0, type: "Service", category: "LABORATORY" },
  { id: 1022, name: "AST (Old Term SGOT)", price: 340.0, type: "Service", category: "LABORATORY" },
  { id: 1023, name: "Bilirubin", price: 340.0, type: "Service", category: "LABORATORY" },
  { id: 1024, name: "Bilirubin (Direct & Indirect)", price: 680.0, type: "Service", category: "LABORATORY" },
  { id: 1025, name: "BUN", price: 340.0, type: "Service", category: "LABORATORY" },
  { id: 1026, name: "Calcium (Ca++)", price: 400.0, type: "Service", category: "LABORATORY" },
  { id: 1027, name: "Cholesterol Package", price: 900.0, type: "Service", category: "LABORATORY" },
  { id: 1028, name: "Cholesterol Screening", price: 500.0, type: "Service", category: "LABORATORY" },
  { id: 1029, name: "CPK", price: 600.0, type: "Service", category: "LABORATORY" },
  { id: 1030, name: "Creatinine", price: 300.0, type: "Service", category: "LABORATORY" },
  { id: 1031, name: "Glucose", price: 180.0, type: "Service", category: "LABORATORY" },
  { id: 1032, name: "Glucose Tolerance Test", price: 530.0, type: "Service", category: "LABORATORY" },
  { id: 1033, name: "Hba1c (Glycohemoglobin)", price: 650.0, type: "Service", category: "LABORATORY" },
  { id: 1034, name: "Magnesium", price: 600.0, type: "Service", category: "LABORATORY" },
  { id: 1035, name: "Phosphorus", price: 400.0, type: "Service", category: "LABORATORY" },
  { id: 1036, name: "Protein, Total Serum", price: 350.0, type: "Service", category: "LABORATORY" },
  { id: 1037, name: "Triglyceride", price: 340.0, type: "Service", category: "LABORATORY" },
  { id: 1038, name: "Troponin-1 (Vidas High Sensitive)", price: 1200.0, type: "Service", category: "LABORATORY" },
  { id: 1039, name: "Uric Acid", price: 400.0, type: "Service", category: "LABORATORY" },
  { id: 1040, name: "FSH (Vidas)", price: 920.0, type: "Service", category: "LABORATORY" },
  { id: 1041, name: "Progesterone (Vidas)", price: 1030.0, type: "Service", category: "LABORATORY" },
  { id: 1042, name: "Prolactin(Vidas)", price: 860.0, type: "Service", category: "LABORATORY" },
  { id: 1043, name: "PSA (Vidas)", price: 1200.0, type: "Service", category: "LABORATORY" },
  { id: 1044, name: "FT4 (Vidas)", price: 700.0, type: "Service", category: "LABORATORY" },
  { id: 1045, name: "TSH (Vidas)", price: 700.0, type: "Service", category: "LABORATORY" },
  { id: 1046, name: "B-hCG Rapid Quantitative test (Vidas)", price: 1200.0, type: "Service", category: "LABORATORY" },
  { id: 1047, name: "Bleeding Time", price: 260.0, type: "Service", category: "LABORATORY" },
  { id: 1048, name: "Bone Marrow Aspirate", price: 660.0, type: "Service", category: "LABORATORY" },
  { id: 1049, name: "CBC", price: 400.0, type: "Service", category: "LABORATORY" },
  { id: 1050, name: "CBC With Diff Package", price: 460.0, type: "Service", category: "LABORATORY" },
  { id: 1051, name: "\"CBC With Diff, MP\" Package", price: 530.0, type: "Service", category: "LABORATORY" },
  { id: 1052, name: "Clotting Time", price: 260.0, type: "Service", category: "LABORATORY" },
  { id: 1053, name: "ESR", price: 230.0, type: "Service", category: "LABORATORY" },
  { id: 1054, name: "Filariae (ICT)", price: 660.0, type: "Service", category: "LABORATORY" },
  { id: 1055, name: "Hb Electrophoresis", price: 600.0, type: "Service", category: "LABORATORY" },
  { id: 1056, name: "Hgb / Hct", price: 400.0, type: "Service", category: "LABORATORY" },
  { id: 1057, name: "Hct", price: 100.0, type: "Service", category: "LABORATORY" },
  { id: 1058, name: "MP (ICT) Pf/Pv", price: 150.0, type: "Service", category: "LABORATORY" },
  { id: 1059, name: "Peripheral Smear", price: 260.0, type: "Service", category: "LABORATORY" },
  { id: 1060, name: "PT / INR", price: 400.0, type: "Service", category: "LABORATORY" },
  { id: 1061, name: "PTT", price: 400.0, type: "Service", category: "LABORATORY" },
  { id: 1062, name: "Retic Count", price: 340.0, type: "Service", category: "LABORATORY" },
  { id: 1063, name: "D-Dimer", price: 960.0, type: "Service", category: "LABORATORY" },
  { id: 1064, name: "Fat", price: 260.0, type: "Service", category: "LABORATORY" },
  { id: 1065, name: "Occult Blood", price: 340.0, type: "Service", category: "LABORATORY" },
  { id: 1066, name: "Stool Direct & Concentrate", price: 230.0, type: "Service", category: "LABORATORY" },
  { id: 1067, name: "ASO", price: 400.0, type: "Service", category: "LABORATORY" },
  { id: 1068, name: "CRP", price: 550.0, type: "Service", category: "LABORATORY" },
  { id: 1069, name: "Chlamydia Device Test", price: 720.0, type: "Service", category: "LABORATORY" },
  { id: 1070, name: "Dengue NS1 & IgM/IgM (Device)", price: 1050.0, type: "Service", category: "LABORATORY" },
  { id: 1071, name: "Dengue NS1 (Vidas)", price: 1050.0, type: "Service", category: "LABORATORY" },
  { id: 1072, name: "Dengue IgM (Vidas)", price: 1050.0, type: "Service", category: "LABORATORY" },
  { id: 1073, name: "Dengue IgG (Vidas)", price: 1400.0, type: "Service", category: "LABORATORY" },
  { id: 1074, name: "HBsAg Strip", price: 350.0, type: "Service", category: "LABORATORY" },
  { id: 1075, name: "HBsAg (Vidas Ultra)", price: 770.0, type: "Service", category: "LABORATORY" },
  { id: 1076, name: "HBsAg (Vidas Ultra Confirmaiton)", price: 1640.0, type: "Service", category: "LABORATORY" },
  { id: 1077, name: "anti-HBs Total II (Vidas)", price: 1780.0, type: "Service", category: "LABORATORY" },
  { id: 1078, name: "HCV Device", price: 360.0, type: "Service", category: "LABORATORY" },
  { id: 1079, name: "HCV (Vidas anti-HCV)", price: 1200.0, type: "Service", category: "LABORATORY" },
  { id: 1080, name: "anti-HBc IgM II (Vidas)", price: 2240.0, type: "Service", category: "LABORATORY" },
  { id: 1081, name: "anti-HBc Total II (Vidas)", price: 1950.0, type: "Service", category: "LABORATORY" },
  { id: 1082, name: "HIV Strip", price: 550.0, type: "Service", category: "LABORATORY" },
  { id: 1083, name: "HIV Ultra (Vidas)", price: 1970.0, type: "Service", category: "LABORATORY" },
  { id: 1084, name: "HIV Quick (Vidas)", price: 1330.0, type: "Service", category: "LABORATORY" },
  { id: 1085, name: "HAV IgM Rapid Test Device", price: 550.0, type: "Service", category: "LABORATORY" },
  { id: 1086, name: "anti-HAV IgM (Vidas)", price: 2590.0, type: "Service", category: "LABORATORY" },
  { id: 1087, name: "anti-HAV Total (Vidas)", price: 1750.0, type: "Service", category: "LABORATORY" },
  { id: 1088, name: "HEV IgM Rapid Test Device", price: 530.0, type: "Service", category: "LABORATORY" },
  { id: 1089, name: "anti-HEV IgG (Vidas)", price: 2720.0, type: "Service", category: "LABORATORY" },
  { id: 1090, name: "H. Pylori Device", price: 400.0, type: "Service", category: "LABORATORY" },
  { id: 1091, name: "H. Pylori IgG (Vidas)", price: 1630.0, type: "Service", category: "LABORATORY" },
  { id: 1092, name: "RPR", price: 260.0, type: "Service", category: "LABORATORY" },
  { id: 1093, name: "Syphilis Ig (Device Test) VDRL", price: 260.0, type: "Service", category: "LABORATORY" },
  { id: 1094, name: "Typhoid IgG/IgM /Feb Agg", price: 330.0, type: "Service", category: "LABORATORY" },
  { id: 1095, name: "Typhoid IgG/IgM with Typhus", price: 500.0, type: "Service", category: "LABORATORY" },
  { id: 1096, name: "\"Typhus OX2, OX19\"", price: 240.0, type: "Service", category: "LABORATORY" },
  { id: 1097, name: "Chikungunya IgM/IgG", price: 860.0, type: "Service", category: "LABORATORY" },
  { id: 1098, name: "Pregnancy Test (Urine)", price: 200.0, type: "Service", category: "LABORATORY" },
  { id: 1099, name: "Urinalysis", price: 250.0, type: "Service", category: "LABORATORY" },
  { id: 1100, name: "Multi Drug Test", price: 1580.0, type: "Service", category: "LABORATORY" },
  { id: 1101, name: "Urine 24 hrs Na+", price: 600.0, type: "Service", category: "LABORATORY" },
  { id: 1102, name: "Urine 24 hrs Ca+", price: 600.0, type: "Service", category: "LABORATORY" },
  { id: 1103, name: "Urine 24 hrs Cl", price: 600.0, type: "Service", category: "LABORATORY" },
  { id: 1104, name: "Urine 24 hrs Na+", price: 600.0, type: "Service", category: "LABORATORY" },
  { id: 1105, name: "Urine 24 hrs Creatinine", price: 600.0, type: "Service", category: "LABORATORY" },
  { id: 1106, name: "Urine 24 hrs K+", price: 600.0, type: "Service", category: "LABORATORY" },
  { id: 1107, name: "Urine 24 hrs Protein", price: 600.0, type: "Service", category: "LABORATORY" },
  { id: 1108, name: "Whole Blood Unit (Drawn)", price: 1300.0, type: "Blood", category: "LABORATORY" },
  { id: 1109, name: "Type & Cross-match Fee", price: 200.0, type: "Test", category: "LABORATORY" },
  { id: 1110, name: "Fresh Frozen Plasma (FFP)", price: 2500.0, type: "Blood", category: "LABORATORY" },
  { id: 1111, name: "Blood Bag Only for auto transfusion in the OR", price: 400.0, type: "Service", category: "LABORATORY" },
  { id: 1112, name: "Coombs", price: 400.0, type: "Service", category: "LABORATORY" },
  { id: 1113, name: "Cross-Match", price: 200.0, type: "Service", category: "LABORATORY" },
  { id: 1114, name: "\"Donor, Hospital\"", price: 1300.0, type: "Service", category: "LABORATORY" },
  { id: 1115, name: "Refund for Unused Donor Blood", price: 530.0, type: "Service", category: "LABORATORY" },
  { id: 1116, name: "Type and Cross-Match & Drawn (brings own donor)", price: 2500.0, type: "Service", category: "LABORATORY" },
  { id: 1117, name: "Type and Cross-Match & Drawn (hospital provides donor)", price: 3800.0, type: "Service", category: "LABORATORY" },
  { id: 1118, name: "Type", price: 200.0, type: "Service", category: "LABORATORY" },
  { id: 1119, name: "Type and Cross-Match (do not draw)", price: 2100.0, type: "Service", category: "LABORATORY" }
];