import { InventoryItem } from '../types';

export const PHARMACY_REGISTRY: Partial<InventoryItem>[] = [
    { name: "Alatrol", price: 3.0, type: "PHARMACY_ITEM", category: "PHARMACY" },
    { name: "Alben DS", price: 4.0, type: "PHARMACY_ITEM", category: "PHARMACY" },
    { name: "Amoxacillin Syr", price: 70.0, type: "Syrup", category: "PHARMACY" },
    { name: "Amoxacillin Cap 250mg", price: 4.0, type: "Capsule", category: "PHARMACY" },
    { name: "Antacid Syr", price: 65.0, type: "Syrup", category: "PHARMACY" },
    { name: "Antihistamine / Histasin", price: 0.25, type: "PHARMACY_ITEM", category: "PHARMACY" },
    { name: "Azithromycin Syr 700mg", price: 85.0, type: "Syrup", category: "PHARMACY" },
    { name: "Azithromycin Tab 500mg", price: 30.0, type: "Tablet", category: "PHARMACY" },
    { name: "Bactrim / Cortem", price: 3.0, type: "PHARMACY_ITEM", category: "PHARMACY" },
    { name: "Bactrim Syr", price: 23.0, type: "Syrup", category: "PHARMACY" },
    { name: "Calcium", price: 8.0, type: "PHARMACY_ITEM", category: "PHARMACY" },
    { name: "Cefixime Syr", price: 138.0, type: "Syrup", category: "PHARMACY" },
    { name: "Cefixime Tab 200mg", price: 30.0, type: "Tablet", category: "PHARMACY" },
    { name: "Cephradine 250mg", price: 6.0, type: "PHARMACY_ITEM", category: "PHARMACY" },
    { name: "Cephradine Syr", price: 50.0, type: "Syrup", category: "PHARMACY" },
    { name: "Doxycycline", price: 2.25, type: "PHARMACY_ITEM", category: "PHARMACY" },
    { name: "Eras 75mg", price: 0.8, type: "PHARMACY_ITEM", category: "PHARMACY" },
    { name: "Flamex Syr", price: 34.0, type: "Syrup", category: "PHARMACY" },
    { name: "Hemorrhoid Oint", price: 85.0, type: "Ointment", category: "PHARMACY" },
    { name: "Ibuprofen / Flamex", price: 1.5, type: "PHARMACY_ITEM", category: "PHARMACY" },
    { name: "Iron", price: 90.0, type: "PHARMACY_ITEM", category: "PHARMACY" },
    { name: "Ispaghula", price: 3.3, type: "PHARMACY_ITEM", category: "PHARMACY" },
    { name: "Ketoprofen", price: 11.0, type: "PHARMACY_ITEM", category: "PHARMACY" },
    { name: "Levamisol", price: 1.0, type: "PHARMACY_ITEM", category: "PHARMACY" },
    { name: "Levamisol Syr", price: 10.0, type: "Syrup", category: "PHARMACY" },
    { name: "Levofloxacin 500mg", price: 15.0, type: "PHARMACY_ITEM", category: "PHARMACY" },
    { name: "Levofloxacin 750mg", price: 20.0, type: "PHARMACY_ITEM", category: "PHARMACY" },
    { name: "Methyl Sal Oint", price: 80.0, type: "Ointment", category: "PHARMACY" },
    { name: "Metronidazole / Flagyl 400mg", price: 1.7, type: "PHARMACY_ITEM", category: "PHARMACY" },
    { name: "Metronidazole / Flagyl 50ml", price: 30.0, type: "PHARMACY_ITEM", category: "PHARMACY" },
    { name: "Moxaclav Syr", price: 220.0, type: "Syrup", category: "PHARMACY" },
    { name: "Moxaclav Tab 375mg", price: 25.0, type: "Tablet", category: "PHARMACY" },
    { name: "Paracetamol Syr", price: 25.0, type: "Syrup", category: "PHARMACY" },
    { name: "Paracetamol Tab", price: 1.0, type: "Tablet", category: "PHARMACY" },
    { name: "Permethrin", price: 60.0, type: "PHARMACY_ITEM", category: "PHARMACY" },
    { name: "Ranitidine/Omeprazole", price: 5.0, type: "PHARMACY_ITEM", category: "PHARMACY" },
    { name: "Salbutamol Inhaler 1bottle(200puff)", price: 250.0, type: "Inhaler", category: "PHARMACY" },
    { name: "Salbutamol Syr", price: 23.0, type: "Syrup", category: "PHARMACY" },
    { name: "Salbutamol Tab", price: 0.44, type: "Tablet", category: "PHARMACY" },
    { name: "Toradol 10mg", price: 12.0, type: "PHARMACY_ITEM", category: "PHARMACY" },
    { name: "Toradol Inj", price: 65.0, type: "Injection", category: "PHARMACY" },
    { name: "Tramadol 50mg", price: 8.5, type: "PHARMACY_ITEM", category: "PHARMACY" },
    { name: "Vit B Complex", price: 0.6, type: "PHARMACY_ITEM", category: "PHARMACY" },
    { name: "Vitamins", price: 2.5, type: "PHARMACY_ITEM", category: "PHARMACY" },
    { name: "Vitamins Syr", price: 80.0, type: "Syrup", category: "PHARMACY" },
    { name: "Amoxycillin Syr 100", price: 70.0, type: "Syrup", category: "PHARMACY" },
    { name: "Antacid Susp 200", price: 65.0, type: "Syrup", category: "PHARMACY" },
    { name: "Aqualax Powder 85", price: 120.0, type: "Powder", category: "PHARMACY" },
    { name: "Baby Zinc Sy 100", price: 30.0, type: "PHARMACY_ITEM", category: "PHARMACY" },
    { name: "Bactrim Susp 60", price: 23.0, type: "Syrup", category: "PHARMACY" },
    { name: "Benadryl Sy/ Adryl 100", price: 45.0, type: "PHARMACY_ITEM", category: "PHARMACY" },
    { name: "Cefixim Sy 50", price: 138.0, type: "PHARMACY_ITEM", category: "PHARMACY" },
    { name: "Cephradin Sy. 100", price: 50.0, type: "PHARMACY_ITEM", category: "PHARMACY" },
    { name: "Chloroquine Sy 60", price: 15.0, type: "PHARMACY_ITEM", category: "PHARMACY" },
    { name: "Ciprofloxacin Sy 60", price: 90.0, type: "PHARMACY_ITEM", category: "PHARMACY" },
    { name: "Dextromethorphan / Brofex 100", price: 40.0, type: "PHARMACY_ITEM", category: "PHARMACY" },
    { name: "Ibuprofen Sy 100", price: 34.0, type: "PHARMACY_ITEM", category: "PHARMACY" },
    { name: "Iron Sy 200", price: 90.0, type: "PHARMACY_ITEM", category: "PHARMACY" },
    { name: "Levamisole Sy 30", price: 10.0, type: "PHARMACY_ITEM", category: "PHARMACY" },
    { name: "Metronidazole / Flagyl Susp 50", price: 30.0, type: "Syrup", category: "PHARMACY" },
    { name: "Milk of Magnesia 100", price: 90.0, type: "PHARMACY_ITEM", category: "PHARMACY" },
    { name: "Moxaclav Sy 100", price: 220.0, type: "PHARMACY_ITEM", category: "PHARMACY" },
    { name: "Paracetamol Susp 60", price: 25.0, type: "Syrup", category: "PHARMACY" },
    { name: "Phenobarb Sy 100", price: 70.0, type: "PHARMACY_ITEM", category: "PHARMACY" },
    { name: "Theophyllin Sy 100", price: 32.0, type: "PHARMACY_ITEM", category: "PHARMACY" },
    { name: "Ventolin Sy 100", price: 23.0, type: "PHARMACY_ITEM", category: "PHARMACY" },
    { name: "Vitamin Drops / Multivit Sy 100", price: 23.0, type: "Drops", category: "PHARMACY" },
    { name: "Zimax Sy 15", price: 85.0, type: "PHARMACY_ITEM", category: "PHARMACY" },
    { name: "Adrenalin Inj 1mg", price: 25.0, type: "Injection", category: "PHARMACY" },
    { name: "Acetaminophen Inj 500mg", price: 150.0, type: "Injection", category: "PHARMACY" },
    { name: "Aldactone Tab 25mg", price: 5.0, type: "Tablet", category: "PHARMACY" },
    { name: "Aldomet Tab Sardopa 250mg", price: 4.0, type: "Tablet", category: "PHARMACY" },
    { name: "Allopurinol Tab (Aluric) 100mg", price: 2.5, type: "Tablet", category: "PHARMACY" },
    { name: "Albendazole Tab 400mg", price: 4.0, type: "Tablet", category: "PHARMACY" },
    { name: "Aminophylin Inj 250mg", price: 18.0, type: "Injection", category: "PHARMACY" },
    { name: "Amoxycillin Cap 250mg", price: 4.0, type: "Capsule", category: "PHARMACY" },
    { name: "Amoxycillin Syr 125mg", price: 70.0, type: "Syrup", category: "PHARMACY" },
    { name: "Amoxycillin Inj 500mg", price: 60.0, type: "Injection", category: "PHARMACY" },
    { name: "Amikacin Inj 500mg", price: 70.0, type: "Injection", category: "PHARMACY" },
    { name: "Amino Acid Inj 10% 1000ml", price: 400.0, type: "Injection", category: "PHARMACY" },
    { name: "Anclog Tab Clopidegrol 75mg", price: 12.0, type: "Tablet", category: "PHARMACY" },
    { name: "Angilock Tab Losartan K(Rakib 50mg", price: 10.0, type: "Tablet", category: "PHARMACY" },
    { name: "Antazol Nasal Drops Xylometazolin 0.001", price: 8.0, type: "Drops", category: "PHARMACY" },
    { name: "Anti Snake Venom", price: 1000.0, type: "PHARMACY_ITEM", category: "PHARMACY" },
    { name: "Antibiotic Skin Out 10gm", price: 44.0, type: "PHARMACY_ITEM", category: "PHARMACY" },
    { name: "Apresolin Inj 20mg", price: 150.0, type: "Injection", category: "PHARMACY" },
    { name: "Aqualax Powder Polyethylene Glycol 85mg", price: 120.0, type: "Powder", category: "PHARMACY" },
    { name: "Aquamephyton Inj Phytonadion 2mg", price: 20.0, type: "Injection", category: "PHARMACY" },
    { name: "Aspirin Tab ASA 75mg", price: 0.8, type: "Tablet", category: "PHARMACY" },
    { name: "Atorvastatin Tab 10mg", price: 12.0, type: "Tablet", category: "PHARMACY" },
    { name: "Atorvastatin Tab 40mg", price: 28.0, type: "Tablet", category: "PHARMACY" },
    { name: "Atropine Inj 0.6mg", price: 10.0, type: "Injection", category: "PHARMACY" },
    { name: "Avelin Tab Amitriptyllin 25mg", price: 1.75, type: "Tablet", category: "PHARMACY" },
    { name: "Antacid Syr 200ml", price: 65.0, type: "Syrup", category: "PHARMACY" },
    { name: "Amitryptyllin Tab 25mg", price: 1.75, type: "Tablet", category: "PHARMACY" },
    { name: "Arlin Tab Linezolid 600mg", price: 85.0, type: "Tablet", category: "PHARMACY" },
    { name: "Arlin Syr 100mg", price: 14.74, type: "Syrup", category: "PHARMACY" },
    { name: "Asmanyl SR Tab Theophyllin 300mg", price: 2.35, type: "Tablet", category: "PHARMACY" },
    { name: "Azithromycin Tab 500mg", price: 30.0, type: "Tablet", category: "PHARMACY" },
    { name: "Azithromycin Sy 15ml 700mg", price: 85.0, type: "PHARMACY_ITEM", category: "PHARMACY" },
    { name: "Augmantin Tab 250mg", price: 22.0, type: "Tablet", category: "PHARMACY" },
    { name: "Augmantin Sy 125mg", price: 7.9, type: "PHARMACY_ITEM", category: "PHARMACY" },
    { name: "Anectin Inj Succinylcholin 1gm", price: 220.0, type: "Injection", category: "PHARMACY" },
    { name: "Amlodipine Tab Kisor 5gm", price: 4.0, type: "Tablet", category: "PHARMACY" },
    { name: "Alatrol Tab Cetirizine Dihydrochloride 10mg", price: 3.0, type: "Tablet", category: "PHARMACY" },
    { name: "Atenolol 50mg", price: 0.76, type: "PHARMACY_ITEM", category: "PHARMACY" },
    { name: "Apaxiban Tab 5mg", price: 20.0, type: "Tablet", category: "PHARMACY" },
    { name: "Bactroban Oint Mupirocin 2%", price: 140.0, type: "Ointment", category: "PHARMACY" },
    { name: "B.C Pill", price: 24.0, type: "PHARMACY_ITEM", category: "PHARMACY" },
    { name: "B.C Pill(Femicon)", price: 45.0, type: "PHARMACY_ITEM", category: "PHARMACY" },
    { name: "Bactrim Syr 60ml", price: 23.0, type: "Syrup", category: "PHARMACY" },
    { name: "Bactrim Ds tab 160/800", price: 3.0, type: "Tablet", category: "PHARMACY" },
    { name: "Benadryl Inj Dipenhydramine 50mg", price: 41.0, type: "Injection", category: "PHARMACY" },
    { name: "Benadryl Syr/ Adryl 10mg", price: 45.0, type: "Syrup", category: "PHARMACY" },
    { name: "Betaloc Tab 50mg", price: 2.0, type: "Tablet", category: "PHARMACY" },
    { name: "Bupivacaine Inj (Ultracaine) 0.005", price: 3.5, type: "Injection", category: "PHARMACY" },
    { name: "Bupivacaine Heavy Inj", price: 30.0, type: "Injection", category: "PHARMACY" },
    { name: "Benzoin Tx", price: 8.5, type: "PHARMACY_ITEM", category: "PHARMACY" },
    { name: "Betadine 1oz", price: 30.0, type: "PHARMACY_ITEM", category: "PHARMACY" },
    { name: "Betnovate Rectal Oint", price: 80.0, type: "Ointment", category: "PHARMACY" },
    { name: "Becotide Inhaler", price: 270.0, type: "Inhaler", category: "PHARMACY" },
    { name: "Bisoprolol 2.5mg", price: 7.0, type: "PHARMACY_ITEM", category: "PHARMACY" },
    { name: "Baelomin", price: 270.0, type: "PHARMACY_ITEM", category: "PHARMACY" },
    { name: "Budicart", price: 200.0, type: "PHARMACY_ITEM", category: "PHARMACY" },
    { name: "Bisocodyl 5mg", price: 1.0, type: "PHARMACY_ITEM", category: "PHARMACY" },
    { name: "Brodyl / Brodil", price: 23.0, type: "PHARMACY_ITEM", category: "PHARMACY" },
    { name: "Bactrocin", price: 44.0, type: "PHARMACY_ITEM", category: "PHARMACY" },
    { name: "Budesonide Ani 0.5mg=1amp", price: 40.0, type: "PHARMACY_ITEM", category: "PHARMACY" },
    { name: "Calcium Carbonate D Tab 500mg", price: 8.0, type: "Tablet", category: "PHARMACY" },
    { name: "Calcium Gluconate Inj 1000mg", price: 35.0, type: "Injection", category: "PHARMACY" },
    { name: "Carbamazipine Tab 200mg", price: 4.0, type: "Tablet", category: "PHARMACY" },
    { name: "Carbimazole 5mg", price: 4.0, type: "PHARMACY_ITEM", category: "PHARMACY" },
    { name: "Cardizem SR Cap Dilatiazem 90mg", price: 6.0, type: "Capsule", category: "PHARMACY" },
    { name: "Captopril Tab 25mg", price: 3.0, type: "Tablet", category: "PHARMACY" },
    { name: "Carvedilol Tab 25mg", price: 8.0, type: "Tablet", category: "PHARMACY" },
    { name: "Caphalexin Cap 250mg", price: 6.0, type: "Capsule", category: "PHARMACY" },
    { name: "Chloramphenicol Eye Drops", price: 20.0, type: "Drops", category: "PHARMACY" },
    { name: "Chloramphenicol Eye Oint", price: 10.0, type: "Ointment", category: "PHARMACY" },
    { name: "Chloroquin P Tab 250mg", price: 1.2, type: "Tablet", category: "PHARMACY" },
    { name: "Chloroquin Sy 80mg", price: 1.65, type: "PHARMACY_ITEM", category: "PHARMACY" },
    { name: "Chloroquin Hydroxy 200mg", price: 12.0, type: "PHARMACY_ITEM", category: "PHARMACY" },
    { name: "Cinaron Tab Cinnerazine(Kishor 09-06-2024) 15mg", price: 1.5, type: "Tablet", category: "PHARMACY" },
    { name: "Coartem Tab Artemether/Lumefantrin 20/120mg", price: 20.0, type: "Tablet", category: "PHARMACY" },
    { name: "Clarithromycin Tab 500mg", price: 45.0, type: "Tablet", category: "PHARMACY" },
    { name: "Clopidegrol Tab 75mg", price: 12.0, type: "Tablet", category: "PHARMACY" },
    { name: "Clindamycin Capsule 300mg", price: 17.0, type: "Capsule", category: "PHARMACY" },
    { name: "Clindamycin Capsule 150mg", price: 9.0, type: "Capsule", category: "PHARMACY" },
    { name: "Comet Tab Metformine 500mg", price: 3.0, type: "Tablet", category: "PHARMACY" },
    { name: "Comet Tab Metformine 850mg", price: 4.6, type: "Tablet", category: "PHARMACY" },
    { name: "Cough Sy 100ml", price: 40.0, type: "PHARMACY_ITEM", category: "PHARMACY" },
    { name: "Cough Sy DM / Brofex Dextromethorphan hbr 100ml", price: 40.0, type: "PHARMACY_ITEM", category: "PHARMACY" },
    { name: "Ciprocin Tab 500mg", price: 10.0, type: "Tablet", category: "PHARMACY" },
    { name: "Ciprocin Sy Ciprofloxacin 250mg", price: 90.0, type: "PHARMACY_ITEM", category: "PHARMACY" },
    { name: "Ciprocin Inj 200mg", price: 65.0, type: "Injection", category: "PHARMACY" },
    { name: "Cipro Ear/Eye Drop Rakib", price: 20.0, type: "Drops", category: "PHARMACY" },
    { name: "Combine 3 puff Ipra Inhealer", price: 250.0, type: "PHARMACY_ITEM", category: "PHARMACY" },
    { name: "Clofenac gel Diclofenac Sod", price: 12.9, type: "Ointment", category: "PHARMACY" },
    { name: "Clofenac Inj 75mg", price: 14.0, type: "Injection", category: "PHARMACY" },
    { name: "Clofenac Tab 50mg", price: 1.0, type: "Tablet", category: "PHARMACY" },
    { name: "Cotrim Sy.", price: 23.0, type: "PHARMACY_ITEM", category: "PHARMACY" },
    { name: "Clofenac SR Tab 100mg", price: 3.0, type: "Tablet", category: "PHARMACY" },
    { name: "Clomid Tab Clomophene Citrate 50mg", price: 10.0, type: "Tablet", category: "PHARMACY" },
    { name: "Cortider Cream Hydrocortisone 20gm 0.01", price: 70.0, type: "Ointment", category: "PHARMACY" },
    { name: "Clexane Inj Exoxapirin 40mg", price: 435.0, type: "Injection", category: "PHARMACY" },
    { name: "Clexane Inj 60mg", price: 575.0, type: "Injection", category: "PHARMACY" },
    { name: "Cefazolin IV 1000mg", price: 210.0, type: "PHARMACY_ITEM", category: "PHARMACY" },
    { name: "Cefixime Cap 200mg", price: 30.0, type: "Capsule", category: "PHARMACY" },
    { name: "Cefixime Sy 100mg", price: 138.0, type: "PHARMACY_ITEM", category: "PHARMACY" },
    { name: "Chlorpromazine 10amp 50-100mg", price: 225.0, type: "PHARMACY_ITEM", category: "PHARMACY" },
    { name: "Ceftazidime Inj 1gm", price: 215.0, type: "Injection", category: "PHARMACY" },
    { name: "Cephradine Sy 125mg", price: 50.0, type: "PHARMACY_ITEM", category: "PHARMACY" },
    { name: "Cephradine Cap 250mg", price: 6.0, type: "Capsule", category: "PHARMACY" },
    { name: "Cephradine Inj 500mg", price: 60.0, type: "Injection", category: "PHARMACY" },
    { name: "Cyclobenzaprin 10mg", price: 3.0, type: "PHARMACY_ITEM", category: "PHARMACY" },
    { name: "Cyclobenzapine 10mg", price: 3.0, type: "PHARMACY_ITEM", category: "PHARMACY" },
    { name: "Ceftron Inj IV 500mg", price: 80.0, type: "Injection", category: "PHARMACY" },
    { name: "Chcocin Eye Drops 0.003", price: 20.0, type: "Drops", category: "PHARMACY" },
    { name: "Chlomomycitin Ear/Eye", price: 20.0, type: "PHARMACY_ITEM", category: "PHARMACY" },
    { name: "Danoil Tab 5mg", price: 0.35, type: "Tablet", category: "PHARMACY" },
    { name: "Diactin Tab Glipizide(Arun) 5mg", price: 1.5, type: "Tablet", category: "PHARMACY" },
    { name: "Dapsone Tab", price: 0.2, type: "Tablet", category: "PHARMACY" },
    { name: "Decason Tab Dexamethasone 0.5mg", price: 1.0, type: "Tablet", category: "PHARMACY" },
    { name: "Decason Inj 4mg", price: 25.0, type: "Injection", category: "PHARMACY" },
    { name: "Dental Floss", price: 60.0, type: "PHARMACY_ITEM", category: "PHARMACY" },
    { name: "Depo Medrol Inj Methylprednisolone 40mg", price: 130.0, type: "Injection", category: "PHARMACY" },
    { name: "Depo Provera Inj", price: 5.0, type: "Injection", category: "PHARMACY" },
    { name: "Depo Medrol 1cc, 2% Xylocaine", price: 130.0, type: "PHARMACY_ITEM", category: "PHARMACY" },
    { name: "Dermazine Cream Silver Sulfadiazine 25mg", price: 40.0, type: "Ointment", category: "PHARMACY" },
    { name: "Dextromethorphan Sy 10mg/tsp", price: 40.0, type: "PHARMACY_ITEM", category: "PHARMACY" },
    { name: "Dipersil Oint", price: 4.0, type: "Ointment", category: "PHARMACY" },
    { name: "Digoxin Tab 0.25mg", price: 1.2, type: "Tablet", category: "PHARMACY" },
    { name: "Digoxin Inj 0.25mg", price: 55.0, type: "Injection", category: "PHARMACY" },
    { name: "Dilantin Tab 100mg", price: 4.0, type: "Tablet", category: "PHARMACY" },
    { name: "Diprosalic Sol", price: 1.0, type: "PHARMACY_ITEM", category: "PHARMACY" },
    { name: "Doxycyclin Cap 100mg", price: 2.25, type: "Capsule", category: "PHARMACY" },
    { name: "Dyazide Tab 25mg", price: 8.0, type: "Tablet", category: "PHARMACY" },
    { name: "Diclofen Tab 50mg", price: 1.0, type: "Tablet", category: "PHARMACY" },
    { name: "Diclofen Inj 75mg", price: 14.0, type: "Injection", category: "PHARMACY" },
    { name: "Diclofen Gel 10gm", price: 12.9, type: "Ointment", category: "PHARMACY" },
    { name: "Diclofen SR Tab Diclofenac Sod 100mg", price: 3.0, type: "Tablet", category: "PHARMACY" },
    { name: "Diltiazem SR Cap 90mg", price: 6.0, type: "Capsule", category: "PHARMACY" },
    { name: "Dextrose Inj 0.25", price: 30.0, type: "Injection", category: "PHARMACY" },
    { name: "Dopamine Inj 200mg", price: 45.0, type: "Injection", category: "PHARMACY" },
    { name: "Dormicum Tab Midazolam 7.5mg", price: 8.0, type: "Tablet", category: "PHARMACY" },
    { name: "Dormicum Inj 15mg", price: 15.0, type: "Injection", category: "PHARMACY" },
    { name: "Duke’s Magic Mouth Wash 1 Bottle", price: 140.0, type: "PHARMACY_ITEM", category: "PHARMACY" },
    { name: "Duralax Tab Bisacodyl Hcl 5mg", price: 1.0, type: "Tablet", category: "PHARMACY" },
    { name: "PPD Per Dose", price: 50.0, type: "PHARMACY_ITEM", category: "PHARMACY" },
    { name: "Doxophyllin 400mg", price: 10.0, type: "PHARMACY_ITEM", category: "PHARMACY" },
    { name: "Doxophyllin 100mg/1tsp 100ml", price: 95.0, type: "PHARMACY_ITEM", category: "PHARMACY" },
    { name: "Daonil Glibenclamide 5mg", price: 0.34, type: "PHARMACY_ITEM", category: "PHARMACY" },
    { name: "Diazide 25mg", price: 6.0, type: "PHARMACY_ITEM", category: "PHARMACY" },
    { name: "Ephedrine Inj 15mg", price: 90.0, type: "Injection", category: "PHARMACY" },
    { name: "Erbolin Tab Methyl Ergometrin 0.125mg", price: 0.55, type: "Tablet", category: "PHARMACY" },
    { name: "Erbolin Inj 0.2mg", price: 3.0, type: "Injection", category: "PHARMACY" },
    { name: "E-Mycin Tab 500mg", price: 8.0, type: "Tablet", category: "PHARMACY" },
    { name: "E-Mycin Sy 125mg", price: 2.95, type: "PHARMACY_ITEM", category: "PHARMACY" },
    { name: "Esomoprazole Tab 20mg", price: 2.5, type: "Tablet", category: "PHARMACY" },
    { name: "Evit Tab 200mg", price: 2.0, type: "Tablet", category: "PHARMACY" },
    { name: "Ecap 200mg", price: 5.0, type: "Capsule", category: "PHARMACY" },
    { name: "Emcil Tab Pivmecillinum (Out of Stock) 200mg", price: 16.0, type: "Tablet", category: "PHARMACY" },
    { name: "Emistat Inj 8mg", price: 30.0, type: "Injection", category: "PHARMACY" },
    { name: "Emistat Tab Ondansetron 8mg", price: 6.0, type: "Tablet", category: "PHARMACY" },
    { name: "Emistat FT Tab 4mg", price: 5.0, type: "Tablet", category: "PHARMACY" },
    { name: "Etoricoxib 60mg", price: 7.0, type: "PHARMACY_ITEM", category: "PHARMACY" },
    { name: "Etroconazole 100mg", price: 15.0, type: "PHARMACY_ITEM", category: "PHARMACY" },
    { name: "Erian Oint/ Rectal Oint", price: 80.0, type: "Ointment", category: "PHARMACY" },
    { name: "Econate Vag Oint.", price: 1000.0, type: "Ointment", category: "PHARMACY" },
    { name: "Ephenephrine 1mg", price: 35.0, type: "PHARMACY_ITEM", category: "PHARMACY" },
    { name: "Enoxaprine 60mg", price: 576.0, type: "PHARMACY_ITEM", category: "PHARMACY" },
    { name: "Estrogen Cream", price: 1000.0, type: "Ointment", category: "PHARMACY" },
    { name: "Empagliflozin 25mg", price: 40.0, type: "PHARMACY_ITEM", category: "PHARMACY" },
    { name: "Emjard 25mg", price: 40.0, type: "PHARMACY_ITEM", category: "PHARMACY" },
    { name: "Famotidine Tab 20mg", price: 3.0, type: "Tablet", category: "PHARMACY" },
    { name: "Filfresh Tab Melatonin 3mg", price: 3.0, type: "Tablet", category: "PHARMACY" },
    { name: "Flagyl Sy 50ml", price: 30.0, type: "PHARMACY_ITEM", category: "PHARMACY" },
    { name: "Flagyl Tab 400mg", price: 1.7, type: "Tablet", category: "PHARMACY" },
    { name: "Flagyl Inj 500mg", price: 60.0, type: "Injection", category: "PHARMACY" },
    { name: "Flexa", price: 5.0, type: "PHARMACY_ITEM", category: "PHARMACY" },
    { name: "Flexor 10mg", price: 3.0, type: "PHARMACY_ITEM", category: "PHARMACY" },
    { name: "Flor-i-Strip", price: 1.0, type: "PHARMACY_ITEM", category: "PHARMACY" },
    { name: "Folfetab 200mg", price: 0.2, type: "Tablet", category: "PHARMACY" },
    { name: "Furadantin Tab Nitrofurantoin 100mg", price: 8.0, type: "Tablet", category: "PHARMACY" },
    { name: "Folneed Tab Folic Acid + Zinc (Rakib) 5mg+20mg", price: 2.0, type: "Tablet", category: "PHARMACY" },
    { name: "Fungidal Cream oizole Nitrate", price: 40.0, type: "Ointment", category: "PHARMACY" },
    { name: "Fungidal HC Cream 15gm", price: 45.0, type: "Ointment", category: "PHARMACY" },
    { name: "Femicon Tab", price: 45.0, type: "Tablet", category: "PHARMACY" },
    { name: "Fluconazole Cap Diflucan 50mg", price: 8.0, type: "Capsule", category: "PHARMACY" },
    { name: "Fluconazole Cap Diflucan 150mg", price: 22.0, type: "Capsule", category: "PHARMACY" },
    { name: "Fluoxitin 20mg", price: 3.0, type: "PHARMACY_ITEM", category: "PHARMACY" },
    { name: "Fludrocortisone Tab 0.001", price: 21.0, type: "Tablet", category: "PHARMACY" },
    { name: "Fastum Gel Ketoprofen 30gm", price: 120.0, type: "Ointment", category: "PHARMACY" },
    { name: "Fentanyl Inj 0.5mg", price: 60.0, type: "Injection", category: "PHARMACY" },
    { name: "Folic Acid (Folicin) 5mg", price: 1.0, type: "PHARMACY_ITEM", category: "PHARMACY" },
    { name: "Feozine", price: 2.0, type: "PHARMACY_ITEM", category: "PHARMACY" },
    { name: "Formatidin", price: 900.0, type: "PHARMACY_ITEM", category: "PHARMACY" },
    { name: "Formatid Inhaler", price: 980.0, type: "Inhaler", category: "PHARMACY" },
    { name: "Gentamycin E/E drops", price: 32.0, type: "Drops", category: "PHARMACY" },
    { name: "Gliclazide 80mg", price: 8.0, type: "PHARMACY_ITEM", category: "PHARMACY" },
    { name: "Gentamycin Inj 80mg", price: 10.0, type: "Injection", category: "PHARMACY" },
    { name: "Gentian Violet 0.02", price: 8.0, type: "PHARMACY_ITEM", category: "PHARMACY" },
    { name: "Gastalfate Tab Sucralfate 500mg", price: 5.0, type: "Tablet", category: "PHARMACY" },
    { name: "Gabapantin 300mg", price: 16.0, type: "PHARMACY_ITEM", category: "PHARMACY" },
    { name: "Glucose Powder 400mg", price: 60.0, type: "Powder", category: "PHARMACY" },
    { name: "Glucose Inj 20ml 0.25", price: 30.0, type: "Injection", category: "PHARMACY" },
    { name: "Glycerin", price: 5.0, type: "PHARMACY_ITEM", category: "PHARMACY" },
    { name: "Glycerin Suppository", price: 5.0, type: "Suppository", category: "PHARMACY" },
    { name: "Gyno-Pevaryl VT 3 Pack", price: 70.0, type: "PHARMACY_ITEM", category: "PHARMACY" },
    { name: "Hemorrhoidal Oint", price: 80.0, type: "Ointment", category: "PHARMACY" },
    { name: "Heparin Inj 5000u", price: 66.0, type: "Injection", category: "PHARMACY" },
    { name: "Halopid tab Haloperidol 5mg", price: 1.0, type: "Tablet", category: "PHARMACY" },
    { name: "Halopid Inj 5mg/ml", price: 10.8, type: "Injection", category: "PHARMACY" },
    { name: "Hibitane OB Cream", price: 90.0, type: "Ointment", category: "PHARMACY" },
    { name: "Hydrocortisone Tab 20mg", price: 31.0, type: "Tablet", category: "PHARMACY" },
    { name: "Hydrocortisone Sod Succ Inj 100mg", price: 70.0, type: "Injection", category: "PHARMACY" },
    { name: "Hydrogen Peroxide", price: 45.0, type: "PHARMACY_ITEM", category: "PHARMACY" },
    { name: "Hydroxychloroquine tab 200mg", price: 12.0, type: "Tablet", category: "PHARMACY" },
    { name: "Hydor Chlorozide 25mg", price: 0.76, type: "PHARMACY_ITEM", category: "PHARMACY" },
    { name: "Hyper-Tet Inj 250u", price: 1050.0, type: "Injection", category: "PHARMACY" },
    { name: "Humilin 70/30 100u", price: 415.0, type: "PHARMACY_ITEM", category: "PHARMACY" },
    { name: "Hiberix Inj Haemophilus Influenzae Type B", price: 3800.0, type: "Injection", category: "PHARMACY" },
    { name: "Hepatitis B Vaccine", price: 550.0, type: "Vaccine", category: "PHARMACY" },
    { name: "Hexiscrub 250ml", price: 300.0, type: "PHARMACY_ITEM", category: "PHARMACY" },
    { name: "HC 1%", price: 70.0, type: "PHARMACY_ITEM", category: "PHARMACY" },
    { name: "Tyrox 25mg", price: 0.76, type: "PHARMACY_ITEM", category: "PHARMACY" },
    { name: "Na Hyaluronate 20mg", price: 2000.0, type: "PHARMACY_ITEM", category: "PHARMACY" },
    { name: "Ibuprofen Tab 400mg", price: 1.5, type: "Tablet", category: "PHARMACY" },
    { name: "Ibuprofen Sy 100mg/tsp", price: 34.0, type: "PHARMACY_ITEM", category: "PHARMACY" },
    { name: "Imovane Tab Zopiclone 2mg", price: 3.0, type: "Tablet", category: "PHARMACY" },
    { name: "Imodium Cap", price: 1.0, type: "Capsule", category: "PHARMACY" },
    { name: "Imiphenam Inj Imiphenam + Cilastin", price: 1000.0, type: "Injection", category: "PHARMACY" },
    { name: "Inderal Tab Propanolol 10mg", price: 0.51, type: "Tablet", category: "PHARMACY" },
    { name: "Inderal Tab Indomethacin 40mg", price: 1.51, type: "Tablet", category: "PHARMACY" },
    { name: "Indocin Cap 25mg", price: 1.0, type: "Capsule", category: "PHARMACY" },
    { name: "Iodine Tx", price: 22.0, type: "PHARMACY_ITEM", category: "PHARMACY" },
    { name: "Iron Sy 200ml", price: 50.0, type: "PHARMACY_ITEM", category: "PHARMACY" },
    { name: "Iron Tab", price: 0.2, type: "Tablet", category: "PHARMACY" },
    { name: "Iron Cap", price: 5.0, type: "Capsule", category: "PHARMACY" },
    { name: "Isordil Tap 10mg", price: 0.35, type: "PHARMACY_ITEM", category: "PHARMACY" },
    { name: "Insulin NPH 100u/ml", price: 0.7, type: "PHARMACY_ITEM", category: "PHARMACY" },
    { name: "Insulin Regular 100u/ml", price: 415.0, type: "PHARMACY_ITEM", category: "PHARMACY" },
    { name: "Isotrex Gel Isotretinoin 0.0005", price: 200.0, type: "Ointment", category: "PHARMACY" },
    { name: "Insulin 70/30 Mixtrand 1000u", price: 415.0, type: "PHARMACY_ITEM", category: "PHARMACY" },
    { name: "Iopamiro 370 Inj 50ml", price: 1000.0, type: "Injection", category: "PHARMACY" },
    { name: "Ivermectin 12mg", price: 20.0, type: "PHARMACY_ITEM", category: "PHARMACY" },
    { name: "Lactolose 100cc", price: 160.0, type: "PHARMACY_ITEM", category: "PHARMACY" },
    { name: "Jasoprim Tab Primaquine 15mg", price: 1.26, type: "Tablet", category: "PHARMACY" },
    { name: "Jasoquine tab Quinine 300mg", price: 6.0, type: "Tablet", category: "PHARMACY" },
    { name: "Jasoquine Inj Quinine Di-hydrochloride 300mg", price: 20.0, type: "Injection", category: "PHARMACY" },
    { name: "KCL Inj / Syr 100ml 20meq", price: 23.0, type: "Injection", category: "PHARMACY" },
    { name: "KCL Tab 8meq", price: 0.62, type: "Tablet", category: "PHARMACY" },
    { name: "KCL IV", price: 22.0, type: "PHARMACY_ITEM", category: "PHARMACY" },
    { name: "Keflex Sy Cephradin 125mg", price: 3.16, type: "PHARMACY_ITEM", category: "PHARMACY" },
    { name: "Keflex Cap 250mg", price: 6.0, type: "Capsule", category: "PHARMACY" },
    { name: "Keflex Inj 500mg", price: 60.0, type: "Injection", category: "PHARMACY" },
    { name: "Ketamine Inj 1mg", price: 1.0, type: "Injection", category: "PHARMACY" },
    { name: "Ketoral Tab Ketoconazole 200mg", price: 12.0, type: "Tablet", category: "PHARMACY" },
    { name: "Ketorolac Tab 10mg", price: 9.0, type: "Tablet", category: "PHARMACY" },
    { name: "Ketorolac / Rolac Inj 30mg", price: 65.0, type: "Injection", category: "PHARMACY" },
    { name: "Kemadrin Tab 5mg", price: 0.8, type: "Tablet", category: "PHARMACY" },
    { name: "KMNO4 Crystals 10gm", price: 5.0, type: "PHARMACY_ITEM", category: "PHARMACY" },
    { name: "KMNO4 1 Bottle", price: 20.0, type: "PHARMACY_ITEM", category: "PHARMACY" },
    { name: "Lanoxin Inj 0.5mg", price: 100.0, type: "Injection", category: "PHARMACY" },
    { name: "Lanoxin tab 0.25mg", price: 1.2, type: "Tablet", category: "PHARMACY" },
    { name: "Lamisil Cream Terbinafin 0.01", price: 97.0, type: "Ointment", category: "PHARMACY" },
    { name: "Largactil Tab 50mg", price: 1.0, type: "Tablet", category: "PHARMACY" },
    { name: "Largactil Inj 50mg", price: 10.0, type: "Injection", category: "PHARMACY" },
    { name: "Lasix Tab Frusemide 40mg", price: 1.0, type: "Tablet", category: "PHARMACY" },
    { name: "Lasix Inj 40mg", price: 15.0, type: "Injection", category: "PHARMACY" },
    { name: "Laxate Sachet", price: 5.0, type: "PHARMACY_ITEM", category: "PHARMACY" },
    { name: "Laxeena Tab", price: 1.25, type: "Tablet", category: "PHARMACY" },
    { name: "Lactolose Sy 100ml", price: 150.0, type: "PHARMACY_ITEM", category: "PHARMACY" },
    { name: "Labetolol Tab Trandate(kishor) 03-08-25 200mg", price: 10.0, type: "Tablet", category: "PHARMACY" },
    { name: "Labetolol Inj 50mg", price: 100.0, type: "Injection", category: "PHARMACY" },
    { name: "Levamisole Sy 30ml", price: 10.0, type: "PHARMACY_ITEM", category: "PHARMACY" },
    { name: "Levamisole Tab 40mg", price: 1.0, type: "Tablet", category: "PHARMACY" },
    { name: "Levofloxacin Tab 500mg", price: 15.0, type: "Tablet", category: "PHARMACY" },
    { name: "Levofloxacin Inj 500mg", price: 110.0, type: "Injection", category: "PHARMACY" },
    { name: "Linezolid Tab 400mg", price: 60.0, type: "Tablet", category: "PHARMACY" },
    { name: "Linezolid Tab 600mg", price: 85.0, type: "Tablet", category: "PHARMACY" },
    { name: "Linezolid Sy 100mg", price: 15.0, type: "PHARMACY_ITEM", category: "PHARMACY" },
    { name: "Loperamide Cap 2mg", price: 0.9, type: "Capsule", category: "PHARMACY" },
    { name: "Loratidine Tab 10mg", price: 3.0, type: "Tablet", category: "PHARMACY" },
    { name: "Losartan K Tab Osartil. 50mg", price: 10.0, type: "Tablet", category: "PHARMACY" },
    { name: "Lotrix Cream Permethrine", price: 50.0, type: "Ointment", category: "PHARMACY" },
    { name: "Lovatin Tab Lovastatin 20mg", price: 8.0, type: "Tablet", category: "PHARMACY" },
    { name: "Levothyroxi 50mcq", price: 2.25, type: "PHARMACY_ITEM", category: "PHARMACY" },
    { name: "Lidocain 1bottle", price: 97.0, type: "PHARMACY_ITEM", category: "PHARMACY" },
    { name: "Mag Sulph Sol", price: 20.0, type: "PHARMACY_ITEM", category: "PHARMACY" },
    { name: "Mag Sulph Inj 500mg", price: 70.0, type: "Injection", category: "PHARMACY" },
    { name: "Maxcef Inj Cefotaxime 500mg", price: 76.0, type: "Injection", category: "PHARMACY" },
    { name: "Melatonin Tab 3mg", price: 3.0, type: "Tablet", category: "PHARMACY" },
    { name: "Milcam Tab Meloxicam 15mg", price: 4.0, type: "Tablet", category: "PHARMACY" },
    { name: "Mannitol Inj 500ml – 20%", price: 160.0, type: "Injection", category: "PHARMACY" },
    { name: "Merazine Tab", price: 2.0, type: "Tablet", category: "PHARMACY" },
    { name: "Meftormin Tab 500mg", price: 3.0, type: "Tablet", category: "PHARMACY" },
    { name: "Metformin Tab 850mg", price: 4.6, type: "Tablet", category: "PHARMACY" },
    { name: "Metherspan Tab 0.125mg", price: 0.55, type: "Tablet", category: "PHARMACY" },
    { name: "Metherspan Inj 0.2mg", price: 3.0, type: "Injection", category: "PHARMACY" },
    { name: "Methotrexate Tab 2.5mg", price: 6.0, type: "Tablet", category: "PHARMACY" },
    { name: "Methyl Salicylate Oint", price: 42.0, type: "Ointment", category: "PHARMACY" },
    { name: "Methylene Blue", price: 288.0, type: "PHARMACY_ITEM", category: "PHARMACY" },
    { name: "Metoprolol Tab 50mg", price: 2.0, type: "Tablet", category: "PHARMACY" },
    { name: "Misoprostol 200mcg", price: 15.0, type: "PHARMACY_ITEM", category: "PHARMACY" },
    { name: "Metoprolol Inj 5mg", price: 120.0, type: "Injection", category: "PHARMACY" },
    { name: "Mineral Oil 30ml=10taka", price: 10.0, type: "PHARMACY_ITEM", category: "PHARMACY" },
    { name: "Modane Tab", price: 1.25, type: "Tablet", category: "PHARMACY" },
    { name: "MOM Milk of Magnesia", price: 90.0, type: "PHARMACY_ITEM", category: "PHARMACY" },
    { name: "Morphine Inj 15mg", price: 100.0, type: "Injection", category: "PHARMACY" },
    { name: "Morphine Tab Ali Azam 15mg", price: 15.0, type: "Tablet", category: "PHARMACY" },
    { name: "Morphine Sy", price: 20.0, type: "PHARMACY_ITEM", category: "PHARMACY" },
    { name: "Monocard Tab Isosorbide 5 Mononitrate 20mg", price: 1.5, type: "Tablet", category: "PHARMACY" },
    { name: "Multivit Tab", price: 1.65, type: "Tablet", category: "PHARMACY" },
    { name: "Multivit Sy 100ml", price: 90.0, type: "PHARMACY_ITEM", category: "PHARMACY" },
    { name: "Mycoststin Vag Tab 3’s", price: 70.0, type: "Tablet", category: "PHARMACY" },
    { name: "Mycoststin Oral Sy 100,000u/ml", price: 50.0, type: "PHARMACY_ITEM", category: "PHARMACY" },
    { name: "Mebendazole Tab 100mg", price: 0.75, type: "Tablet", category: "PHARMACY" },
    { name: "Meningococcal A+C Vaccine", price: 1000.0, type: "Vaccine", category: "PHARMACY" },
    { name: "Methergin Inj 0.2mg", price: 3.0, type: "Injection", category: "PHARMACY" },
    { name: "Methergin Tab 0.125mg", price: 0.55, type: "Tablet", category: "PHARMACY" },
    { name: "Metronidazole Sy 200mg", price: 2.73, type: "PHARMACY_ITEM", category: "PHARMACY" },
    { name: "Metronidazole Tab 400mg", price: 1.44, type: "Tablet", category: "PHARMACY" },
    { name: "Midazolam Tab 7.5mg", price: 8.0, type: "Tablet", category: "PHARMACY" },
    { name: "Midazolam Sy 15mg", price: 15.0, type: "PHARMACY_ITEM", category: "PHARMACY" },
    { name: "Moxaclav Tab 250mg", price: 25.0, type: "Tablet", category: "PHARMACY" },
    { name: "Moxaclav Sy 100mg", price: 220.0, type: "PHARMACY_ITEM", category: "PHARMACY" },
    { name: "Moxaclav Inj Amoxycillin 1gm + Clavu 200mg 1200mg", price: 310.0, type: "Injection", category: "PHARMACY" },
    { name: "Motigut Tab Domperidone 10mg", price: 2.0, type: "Tablet", category: "PHARMACY" },
    { name: "Montelukast 10mg", price: 10.0, type: "PHARMACY_ITEM", category: "PHARMACY" },
    { name: "Mefenamic Acid Not Available 500mg", price: 1.5, type: "PHARMACY_ITEM", category: "PHARMACY" },
    { name: "Nalidixic Acid Tab 500mg", price: 4.0, type: "Tablet", category: "PHARMACY" },
    { name: "Nalidixic Acid Sy 300mg", price: 3.42, type: "PHARMACY_ITEM", category: "PHARMACY" },
    { name: "Nalbun Inj Nalbuphine 20mg", price: 100.0, type: "Injection", category: "PHARMACY" },
    { name: "Nebanol Oint 10gm", price: 44.0, type: "Ointment", category: "PHARMACY" },
    { name: "Neem Soap", price: 9.0, type: "PHARMACY_ITEM", category: "PHARMACY" },
    { name: "Nefopam Tab 30mg", price: 3.0, type: "Tablet", category: "PHARMACY" },
    { name: "Nefopam Inj 20mg", price: 15.0, type: "Injection", category: "PHARMACY" },
    { name: "Neomycin Tab", price: 8.75, type: "Tablet", category: "PHARMACY" },
    { name: "Neomycin", price: 44.0, type: "PHARMACY_ITEM", category: "PHARMACY" },
    { name: "Neomarkazole 5mg", price: 4.0, type: "PHARMACY_ITEM", category: "PHARMACY" },
    { name: "Nexpro Tab Esomoprazole 20mg", price: 2.5, type: "Tablet", category: "PHARMACY" },
    { name: "Esmoprazole IV", price: 120.0, type: "PHARMACY_ITEM", category: "PHARMACY" },
    { name: "Nifecard Tab Nifedipine 10mg", price: 0.35, type: "Tablet", category: "PHARMACY" },
    { name: "Nifecard SR Tab 20mg", price: 0.66, type: "Tablet", category: "PHARMACY" },
    { name: "Niketheminde Inj", price: 1.0, type: "Injection", category: "PHARMACY" },
    { name: "Niramin Tab Chlorpheniramine Maleate 4mg", price: 0.21, type: "Tablet", category: "PHARMACY" },
    { name: "Niramin Tab Chlorpheniramine Maleate 4mg", price: 0.35, type: "Tablet", category: "PHARMACY" },
    { name: "Niramin Sy 2mg", price: 0.53, type: "PHARMACY_ITEM", category: "PHARMACY" },
    { name: "Nitazoxanide Tab 500mg", price: 10.0, type: "Tablet", category: "PHARMACY" },
    { name: "Nitazoxanide Sy 100mg", price: 50.0, type: "PHARMACY_ITEM", category: "PHARMACY" },
    { name: "Nitrofurantoin Tab 100mg", price: 8.0, type: "Tablet", category: "PHARMACY" },
    { name: "Nitromint Aerosol Nitro Spray 0.4mg", price: 250.0, type: "Drops", category: "PHARMACY" },
    { name: "Nivaquine P Tab Chloroquine 155mg base", price: 1.2, type: "Tablet", category: "PHARMACY" },
    { name: "Nivaquine P Sy 50mg base", price: 1.36, type: "PHARMACY_ITEM", category: "PHARMACY" },
    { name: "Notezine Tab Diethyl Carbomazine 50mg", price: 0.75, type: "Tablet", category: "PHARMACY" },
    { name: "Novatrax Tab Levamisole 40gm", price: 1.0, type: "Tablet", category: "PHARMACY" },
    { name: "Norcolut Tab Norethisterone 5mg", price: 6.0, type: "Tablet", category: "PHARMACY" },
    { name: "Neostegmine Inj 0.5mg", price: 20.0, type: "Injection", category: "PHARMACY" },
    { name: "Neo-Synephrine Nasal Drops", price: 8.0, type: "Drops", category: "PHARMACY" },
    { name: "Norsol", price: 30.0, type: "PHARMACY_ITEM", category: "PHARMACY" },
    { name: "Neuro B", price: 9.0, type: "PHARMACY_ITEM", category: "PHARMACY" },
    { name: "Norcuron Inj", price: 32.0, type: "Injection", category: "PHARMACY" },
    { name: "Norculet Ani (02-12-2024) 5mg", price: 6.5, type: "PHARMACY_ITEM", category: "PHARMACY" },
    { name: "Nystatin 1 Bottle (30cc)", price: 46.0, type: "PHARMACY_ITEM", category: "PHARMACY" },
    { name: "Nandrolone Inj 50mg", price: 240.0, type: "Injection", category: "PHARMACY" },
    { name: "NS Drop / Norsol Drop 25ml", price: 35.0, type: "Drops", category: "PHARMACY" },
    { name: "Nomi 2.5mg", price: 25.0, type: "PHARMACY_ITEM", category: "PHARMACY" },
    { name: "Oradexon Tab 0.5mg", price: 1.0, type: "Tablet", category: "PHARMACY" },
    { name: "Oradexon Inj 5mg", price: 26.0, type: "Injection", category: "PHARMACY" },
    { name: "Oroxin Tab 0.05mg", price: 2.25, type: "Tablet", category: "PHARMACY" },
    { name: "ORS ½ liter", price: 4.0, type: "PHARMACY_ITEM", category: "PHARMACY" },
    { name: "ORS Testy ½ liter", price: 5.0, type: "PHARMACY_ITEM", category: "PHARMACY" },
    { name: "Herbalyte Herbal ORS ½ liter", price: 5.0, type: "PHARMACY_ITEM", category: "PHARMACY" },
    { name: "Ovral Tab / B.C Pill", price: 45.0, type: "Tablet", category: "PHARMACY" },
    { name: "Oxytocin Inj 10 units", price: 25.0, type: "Injection", category: "PHARMACY" },
    { name: "Ofloxacin Tab 200mg", price: 12.0, type: "Tablet", category: "PHARMACY" },
    { name: "Omeprazole Inj 40mg", price: 60.0, type: "Injection", category: "PHARMACY" },
    { name: "Omeprazole Cap 20mg", price: 5.0, type: "Capsule", category: "PHARMACY" },
    { name: "Osmosol Inj Mannitol – 20% 500ml", price: 160.0, type: "Injection", category: "PHARMACY" },
    { name: "Ostocal D Tab Cal Carbonate & D 500mg", price: 5.0, type: "Tablet", category: "PHARMACY" },
    { name: "Ovestin Tab Estriol 1mg", price: 9.0, type: "Tablet", category: "PHARMACY" },
    { name: "Ovestin Cream Estriol 1mg/gm", price: 1000.0, type: "Ointment", category: "PHARMACY" },
    { name: "Ostel D Tab Alendronate Vit D 2800u 70mg", price: 30.0, type: "Tablet", category: "PHARMACY" },
    { name: "Ostel Tab Alendronate 70mg", price: 25.0, type: "Tablet", category: "PHARMACY" },
    { name: "Ondansetron IV", price: 40.0, type: "PHARMACY_ITEM", category: "PHARMACY" },
    { name: "Otosil 10mg", price: 0.5, type: "PHARMACY_ITEM", category: "PHARMACY" },
    { name: "Panwarfin Tab Sod Warfarin 5mg", price: 4.0, type: "Tablet", category: "PHARMACY" },
    { name: "Palonasetron Tab 0.5mg", price: 20.0, type: "Tablet", category: "PHARMACY" },
    { name: "Paracetamol bisository 250mg", price: 5.0, type: "PHARMACY_ITEM", category: "PHARMACY" },
    { name: "Paracetamol Sy 120mg", price: 25.0, type: "PHARMACY_ITEM", category: "PHARMACY" },
    { name: "Paracetamol Tab 500mg", price: 1.0, type: "Tablet", category: "PHARMACY" },
    { name: "Paracetamol inj 1000mg", price: 120.0, type: "Injection", category: "PHARMACY" },
    { name: "Pam Inj Pralidoxime Iodide 500mg", price: 500.0, type: "Injection", category: "PHARMACY" },
    { name: "Penadur LA Inj 12 lac", price: 40.0, type: "Injection", category: "PHARMACY" },
    { name: "Penicillin Tab 250mg", price: 1.52, type: "Tablet", category: "PHARMACY" },
    { name: "Penicillin G 1.2million unit", price: 30.0, type: "PHARMACY_ITEM", category: "PHARMACY" },
    { name: "Pivmecillinum Tab 200mg", price: 16.0, type: "Tablet", category: "PHARMACY" },
    { name: "Perkinil Tab Cyclidine 5mg", price: 0.8, type: "Tablet", category: "PHARMACY" },
    { name: "Pethidine Inj 100mg", price: 100.0, type: "Injection", category: "PHARMACY" },
    { name: "Phenergan Inj 50mg", price: 5.0, type: "Injection", category: "PHARMACY" },
    { name: "Phenergan Tab 25mg", price: 1.0, type: "Tablet", category: "PHARMACY" },
    { name: "Phenergan Tab 10mg", price: 0.5, type: "Tablet", category: "PHARMACY" },
    { name: "Phenobarbitone Tab 60mg", price: 1.5, type: "Tablet", category: "PHARMACY" },
    { name: "Phenobarbitone Inj 200mg", price: 16.0, type: "Injection", category: "PHARMACY" },
    { name: "Phenobarb Sy 20mg/1tsp", price: 70.0, type: "PHARMACY_ITEM", category: "PHARMACY" },
    { name: "Pneumovax Inj Thalassemia", price: 7300.0, type: "Injection", category: "PHARMACY" },
    { name: "Prednisolone Tab 5mg", price: 1.7, type: "Tablet", category: "PHARMACY" },
    { name: "Prednisolone Tab 20mg", price: 6.3, type: "Tablet", category: "PHARMACY" },
    { name: "Propofol 1 20ml", price: 325.0, type: "PHARMACY_ITEM", category: "PHARMACY" },
    { name: "Premarine Tab 0.625mg", price: 30.0, type: "Tablet", category: "PHARMACY" },
    { name: "Premaquine Tab 15mg", price: 1.26, type: "Tablet", category: "PHARMACY" },
    { name: "Propanin Tab 15mg", price: 0.3, type: "Tablet", category: "PHARMACY" },
    { name: "Prostigmine Inj 0.5mg", price: 10.0, type: "Injection", category: "PHARMACY" },
    { name: "Proctosedyl Oint", price: 80.0, type: "Ointment", category: "PHARMACY" },
    { name: "Pantoprezole Tab 40mg", price: 6.0, type: "Tablet", category: "PHARMACY" },
    { name: "Pyridoxin Tab Vit. B6 25mg", price: 2.0, type: "Tablet", category: "PHARMACY" },
    { name: "Pyrintin Tab Dipyridamol 50mg", price: 1.33, type: "Tablet", category: "PHARMACY" },
    { name: "Pantothal Inj Thiopantone Sod 500mg", price: 143.0, type: "Injection", category: "PHARMACY" },
    { name: "Pavulon Inj 2mg", price: 69.6, type: "Injection", category: "PHARMACY" },
    { name: "Profesi / Pregnyl Inj 500mg", price: 456.0, type: "Injection", category: "PHARMACY" },
    { name: "P.P.D Skin Test", price: 50.0, type: "PHARMACY_ITEM", category: "PHARMACY" },
    { name: "Profenid Inj Ketoprofen 100mg", price: 30.0, type: "Injection", category: "PHARMACY" },
    { name: "Profenid SR Cap 100mg", price: 11.0, type: "Capsule", category: "PHARMACY" },
    { name: "Profenid CR Out of Stock", price: 20.0, type: "PHARMACY_ITEM", category: "PHARMACY" },
    { name: "Propofol Inj 100mg", price: 170.0, type: "Injection", category: "PHARMACY" },
    { name: "Prazosin 2mg", price: 6.0, type: "PHARMACY_ITEM", category: "PHARMACY" },
    { name: "Propanolol 40mg", price: 1.5, type: "PHARMACY_ITEM", category: "PHARMACY" },
    { name: "Propanolol 10mg", price: 0.5, type: "PHARMACY_ITEM", category: "PHARMACY" },
    { name: "Prolert Prozac/Fluoxetine 20mg", price: 3.0, type: "PHARMACY_ITEM", category: "PHARMACY" },
    { name: "Progabolin / Pregabolin Stock Out 300mg", price: 16.0, type: "PHARMACY_ITEM", category: "PHARMACY" },
    { name: "Phenylephrin 1cc", price: 10.0, type: "PHARMACY_ITEM", category: "PHARMACY" },
    { name: "Quinine Inj 300mg", price: 20.0, type: "Injection", category: "PHARMACY" },
    { name: "Quinine Tab 300mg", price: 6.0, type: "Tablet", category: "PHARMACY" },
    { name: "Ranitidine Inj 50mg", price: 10.0, type: "Injection", category: "PHARMACY" },
    { name: "Rabies Vaccine 50.00tk / Dose", price: 500.0, type: "Vaccine", category: "PHARMACY" },
    { name: "Rabies Immunoglobulin 1000iu", price: 1000.0, type: "PHARMACY_ITEM", category: "PHARMACY" },
    { name: "Regular Insulin 100u", price: 415.0, type: "PHARMACY_ITEM", category: "PHARMACY" },
    { name: "Rimactazid Tab 300/150", price: 11.5, type: "Tablet", category: "PHARMACY" },
    { name: "Rimstar 4 FDC Tab", price: 20.0, type: "Tablet", category: "PHARMACY" },
    { name: "Rex Tab Antioxidant", price: 2.5, type: "Tablet", category: "PHARMACY" },
    { name: "Rocephine Inj Ceftriaxone 500mg", price: 140.0, type: "Injection", category: "PHARMACY" },
    { name: "Rofecoxib Tab Cox-2 Inhibitor 25mg", price: 3.54, type: "Tablet", category: "PHARMACY" },
    { name: "Rivavoxobon / Rivavoyobon 10mg", price: 25.0, type: "PHARMACY_ITEM", category: "PHARMACY" },
    { name: "Risedronate 5mg", price: 8.0, type: "PHARMACY_ITEM", category: "PHARMACY" },
    { name: "Scabic / Whitfield Oint", price: 13.17, type: "Ointment", category: "PHARMACY" },
    { name: "Simvastatin Tab 10mg", price: 8.0, type: "Tablet", category: "PHARMACY" },
    { name: "Silicote Oint", price: 1.0, type: "Ointment", category: "PHARMACY" },
    { name: "Silvadane Cream Silver Sulphadiazine 25mg", price: 60.0, type: "Ointment", category: "PHARMACY" },
    { name: "Sod. Sulphacetamide Eye Drops", price: 28.0, type: "Drops", category: "PHARMACY" },
    { name: "Sod. Valproate Tab 200mg", price: 2.5, type: "Tablet", category: "PHARMACY" },
    { name: "Sofradex Eye / Ear Drops", price: 45.0, type: "Drops", category: "PHARMACY" },
    { name: "Solu-Cortef Inj Hydrocortisone Sod. Succinate 100mg", price: 60.0, type: "Injection", category: "PHARMACY" },
    { name: "Stemetil Tab 5mg", price: 0.46, type: "Tablet", category: "PHARMACY" },
    { name: "Streptokynase Inj 1.5mill", price: 3100.0, type: "Injection", category: "PHARMACY" },
    { name: "Synalar / Skinalar Cream Fluocinolone", price: 40.0, type: "Ointment", category: "PHARMACY" },
    { name: "Syntocinin Inj 10 units", price: 25.0, type: "Injection", category: "PHARMACY" },
    { name: "Secnidal Tab Secnidazole 1gm", price: 20.0, type: "Tablet", category: "PHARMACY" },
    { name: "Succinylcholin Inj 1gm", price: 220.0, type: "Injection", category: "PHARMACY" },
    { name: "Sucralfate Tab 500mg", price: 5.0, type: "Tablet", category: "PHARMACY" },
    { name: "Sodium Hyaluronte 20mg 20mg", price: 1510.0, type: "PHARMACY_ITEM", category: "PHARMACY" },
    { name: "Spironolactone 25mg", price: 5.0, type: "PHARMACY_ITEM", category: "PHARMACY" },
    { name: "Sitagliptin Indoor Patient Only 50mg", price: 15.0, type: "PHARMACY_ITEM", category: "PHARMACY" },
    { name: "T.T", price: 10.0, type: "PHARMACY_ITEM", category: "PHARMACY" },
    { name: "T.T NG", price: 80.0, type: "PHARMACY_ITEM", category: "PHARMACY" },
    { name: "Taloin Oint", price: 1.0, type: "Ointment", category: "PHARMACY" },
    { name: "Trameinolone 40mg Steroid 40mg", price: 130.0, type: "PHARMACY_ITEM", category: "PHARMACY" },
    { name: "Tamsulosin Cap 0.4mg", price: 12.0, type: "Capsule", category: "PHARMACY" },
    { name: "Tazopen Inj Tazobactam+Pipercillin 4.5gm", price: 1000.0, type: "Injection", category: "PHARMACY" },
    { name: "Tebrazide Tab Pyrazinamide 500mg", price: 2.35, type: "Tablet", category: "PHARMACY" },
    { name: "Tegretol Tab Carbamazipine 200mg", price: 4.0, type: "Tablet", category: "PHARMACY" },
    { name: "Tenormin Tab Atenolol 50mg", price: 0.76, type: "Tablet", category: "PHARMACY" },
    { name: "Tetmosol 30ml", price: 80.0, type: "PHARMACY_ITEM", category: "PHARMACY" },
    { name: "Tetracyclin Cap 250mg", price: 3.0, type: "Capsule", category: "PHARMACY" },
    { name: "Theophyllin Sy 60mg", price: 32.0, type: "PHARMACY_ITEM", category: "PHARMACY" },
    { name: "Theophyllin SR Tab 300mg", price: 2.3, type: "Tablet", category: "PHARMACY" },
    { name: "Thyroxin Tab 50mcg", price: 2.25, type: "Tablet", category: "PHARMACY" },
    { name: "Tigecycline Inj 50mg", price: 600.0, type: "Injection", category: "PHARMACY" },
    { name: "Trandate Tab Lebetolol 200mg", price: 10.0, type: "Tablet", category: "PHARMACY" },
    { name: "Tx Belladona", price: 10.0, type: "PHARMACY_ITEM", category: "PHARMACY" },
    { name: "Tetanus Immune Globulin Inj 250u", price: 1050.0, type: "Injection", category: "PHARMACY" },
    { name: "Tracrium Inj", price: 142.0, type: "Injection", category: "PHARMACY" },
    { name: "Tramal Cap 50mg", price: 8.0, type: "Capsule", category: "PHARMACY" },
    { name: "Tramal Inj 100mg", price: 35.0, type: "Injection", category: "PHARMACY" },
    { name: "Toradol Tab Ketorolac 10mg", price: 12.0, type: "Tablet", category: "PHARMACY" },
    { name: "Torel", price: 70.0, type: "PHARMACY_ITEM", category: "PHARMACY" },
    { name: "Tamoxifen Tab 20mg", price: 15.0, type: "Tablet", category: "PHARMACY" },
    { name: "Toradol Inj 30mg", price: 65.0, type: "Injection", category: "PHARMACY" },
    { name: "Thiamin Out of stock 1cc=100mg", price: 30.0, type: "PHARMACY_ITEM", category: "PHARMACY" },
    { name: "Thiamin 100mg", price: 2.0, type: "PHARMACY_ITEM", category: "PHARMACY" },
    { name: "Triamicinalone 1cc 40mg", price: 130.0, type: "PHARMACY_ITEM", category: "PHARMACY" },
    { name: "Triamicinalone Cream", price: 140.0, type: "Ointment", category: "PHARMACY" },
    { name: "TXA Arun 08-12-2024 500mg", price: 15.0, type: "PHARMACY_ITEM", category: "PHARMACY" },
    { name: "Tranexamic Acid 500mg", price: 76.0, type: "PHARMACY_ITEM", category: "PHARMACY" },
    { name: "TXA Inj 500mg", price: 76.0, type: "Injection", category: "PHARMACY" },
    { name: "Trimetazide 35mg", price: 9.0, type: "PHARMACY_ITEM", category: "PHARMACY" },
    { name: "Tute Net", price: 500.0, type: "PHARMACY_ITEM", category: "PHARMACY" },
    { name: "Ultracarbon Tab Charcoal", price: 9.0, type: "Tablet", category: "PHARMACY" },
    { name: "Ultracaine Inj Bupivacaine 0.005", price: 3.5, type: "Injection", category: "PHARMACY" },
    { name: "Ultracaine Heavy Inj", price: 30.0, type: "Injection", category: "PHARMACY" },
    { name: "Uromax Cap Tamsulosin 0.4mg", price: 10.0, type: "Capsule", category: "PHARMACY" },
    { name: "Vallum Inj Diazepam 10mg", price: 4.0, type: "Injection", category: "PHARMACY" },
    { name: "Vallum Tab 5mg", price: 0.76, type: "Tablet", category: "PHARMACY" },
    { name: "Valex Tab Valproic Acid 200mg", price: 4.0, type: "Tablet", category: "PHARMACY" },
    { name: "Vaseline", price: 30.0, type: "PHARMACY_ITEM", category: "PHARMACY" },
    { name: "Ventolin Sy Salbutamol 2mg=1tsp 100ml", price: 23.0, type: "PHARMACY_ITEM", category: "PHARMACY" },
    { name: "Ventolin Tab 4mg", price: 0.44, type: "Tablet", category: "PHARMACY" },
    { name: "Ventolin Inhaler", price: 195.0, type: "Inhaler", category: "PHARMACY" },
    { name: "Vantolin Respirator Sol Salbutamol Sol 0.1, 0.2, 0.3ml", price: 90.0, type: "PHARMACY_ITEM", category: "PHARMACY" },
    { name: "Versed Inj", price: 15.0, type: "Injection", category: "PHARMACY" },
    { name: "Versed Tab 7.5mg", price: 12.0, type: "Tablet", category: "PHARMACY" },
    { name: "Vibramycin Cap 100mg", price: 2.15, type: "Capsule", category: "PHARMACY" },
    { name: "Vinegar White", price: 5.0, type: "PHARMACY_ITEM", category: "PHARMACY" },
    { name: "Vinegar Dark", price: 2.0, type: "PHARMACY_ITEM", category: "PHARMACY" },
    { name: "Vinegar Douche", price: 8.0, type: "PHARMACY_ITEM", category: "PHARMACY" },
    { name: "Vinegar Ear Drops 1Oz", price: 10.0, type: "Drops", category: "PHARMACY" },
    { name: "Vioform Oint", price: 1.0, type: "Ointment", category: "PHARMACY" },
    { name: "Vit A Cap 50000u", price: 2.0, type: "Capsule", category: "PHARMACY" },
    { name: "Vit A+D Cap", price: 1.0, type: "Capsule", category: "PHARMACY" },
    { name: "Vit B1 Inj Thiamine Hcl", price: 3.2, type: "Injection", category: "PHARMACY" },
    { name: "Vit B2 Tab Riboflavin", price: 0.1, type: "Tablet", category: "PHARMACY" },
    { name: "Vit B6 Tab Pyridoxin Hcl 20mg", price: 2.0, type: "Tablet", category: "PHARMACY" },
    { name: "Vit B12 Inj Cyanocobalamine 1000mcg", price: 20.0, type: "Injection", category: "PHARMACY" },
    { name: "Vit B Complex Tab", price: 0.6, type: "Tablet", category: "PHARMACY" },
    { name: "Vit C Tab Ascorbic Acid 250mg", price: 1.9, type: "Tablet", category: "PHARMACY" },
    { name: "Vit D3 Inj Cholecalciferol 200000u", price: 130.0, type: "Injection", category: "PHARMACY" },
    { name: "Vit D Tab Cholecalciferol 20000u", price: 20.0, type: "Tablet", category: "PHARMACY" },
    { name: "Vit E Tab 200mg", price: 2.0, type: "Tablet", category: "PHARMACY" },
    { name: "Vit E Cap 400iu", price: 5.0, type: "Capsule", category: "PHARMACY" },
    { name: "Vit K Inj Phytonadion 2mg", price: 20.0, type: "Injection", category: "PHARMACY" },
    { name: "Vitamin Sy 100ml", price: 80.0, type: "PHARMACY_ITEM", category: "PHARMACY" },
    { name: "Vitamin (Multi+Minerals) Tab", price: 2.5, type: "Tablet", category: "PHARMACY" },
    { name: "Vildagliptin Outside Patient 50mg", price: 16.0, type: "PHARMACY_ITEM", category: "PHARMACY" },
    { name: "Vermox Tab 100mg", price: 0.76, type: "Tablet", category: "PHARMACY" },
    { name: "Voltaren Inj 75mg", price: 14.0, type: "Injection", category: "PHARMACY" },
    { name: "Valsartan INN 80mg", price: 8.53, type: "PHARMACY_ITEM", category: "PHARMACY" },
    { name: "Vecuronium 10mg", price: 280.0, type: "PHARMACY_ITEM", category: "PHARMACY" },
    { name: "Whitfield Oint 25gm/tube", price: 13.17, type: "Ointment", category: "PHARMACY" },
    { name: "Witch Hazel", price: 1.0, type: "PHARMACY_ITEM", category: "PHARMACY" },
    { name: "Xylocaine 0.01", price: 0.5, type: "PHARMACY_ITEM", category: "PHARMACY" },
    { name: "Xylocaine 0.02", price: 1.0, type: "PHARMACY_ITEM", category: "PHARMACY" },
    { name: "Xylocaine with AD 0.02", price: 1.5, type: "PHARMACY_ITEM", category: "PHARMACY" },
    { name: "Xylocaine Spinal 0.05", price: 30.0, type: "PHARMACY_ITEM", category: "PHARMACY" },
    { name: "Xylocaine Oint/Jelly", price: 97.0, type: "Ointment", category: "PHARMACY" },
    { name: "Xylocaine Spray 0.1", price: 1.15, type: "Drops", category: "PHARMACY" },
    { name: "Xylometazolin Nasal Drops 0.001", price: 8.0, type: "Drops", category: "PHARMACY" },
    { name: "X-Ripa Tab 30mg", price: 3.0, type: "Tablet", category: "PHARMACY" },
    { name: "X-Ripa Inj 20mg", price: 15.0, type: "Injection", category: "PHARMACY" },
    { name: "Zestril Tab Lisinopril 10mg", price: 7.0, type: "Tablet", category: "PHARMACY" },
    { name: "Baby Zinc Sy Zinc Sulphate 10mg", price: 30.0, type: "PHARMACY_ITEM", category: "PHARMACY" },
    { name: "Baby Zinc Tab 20mg", price: 2.0, type: "Tablet", category: "PHARMACY" },
    { name: "Zinc Tab 20mg", price: 1.0, type: "Tablet", category: "PHARMACY" },
    { name: "Zolmitriptan Tab 2.5mg", price: 25.0, type: "Tablet", category: "PHARMACY" },
    { name: "Zopilon Tab Eszopiclone 2mg", price: 3.0, type: "Tablet", category: "PHARMACY" },
    { name: "Zovirax Tab Acyclovir 400mg", price: 22.0, type: "Tablet", category: "PHARMACY" },
    { name: "Zimax Sy Azithromycin 200mg=1tsp 600mg", price: 85.0, type: "PHARMACY_ITEM", category: "PHARMACY" },
    { name: "Zimax Tab 500mg", price: 30.0, type: "Tablet", category: "PHARMACY" },
    { name: "Ziff Cap Zinc, Fe. Sulfate & Folic Acid", price: 4.0, type: "Capsule", category: "PHARMACY" },
    { name: "Zitum Inj Ceftazidime 1gm", price: 215.0, type: "Injection", category: "PHARMACY" },
    { name: "Zinacef Inj Cefurozime 750mg", price: 125.0, type: "Injection", category: "PHARMACY" },
    { name: "Zimox 500mg", price: 30.0, type: "PHARMACY_ITEM", category: "PHARMACY" },
    { name: "Alkoferin", price: 0.83, type: "PHARMACY_ITEM", category: "PHARMACY" },
    { name: "Aramine", price: 0.83, type: "PHARMACY_ITEM", category: "PHARMACY" },
    { name: "Brevedil E", price: 0.83, type: "PHARMACY_ITEM", category: "PHARMACY" },
    { name: "Curare", price: 0.83, type: "PHARMACY_ITEM", category: "PHARMACY" },
    { name: "Droperidol", price: 0.83, type: "Drops", category: "PHARMACY" },
    { name: "Gallemine/Flaxedil", price: 0.83, type: "PHARMACY_ITEM", category: "PHARMACY" },
    { name: "Inderol", price: 0.83, type: "PHARMACY_ITEM", category: "PHARMACY" },
    { name: "Innover", price: 0.83, type: "PHARMACY_ITEM", category: "PHARMACY" },
    { name: "Intropin/Dopamine", price: 0.83, type: "PHARMACY_ITEM", category: "PHARMACY" },
    { name: "Levophed", price: 0.83, type: "PHARMACY_ITEM", category: "PHARMACY" },
    { name: "Lorfan", price: 0.83, type: "PHARMACY_ITEM", category: "PHARMACY" },
    { name: "Mannitol IV", price: 130.0, type: "PHARMACY_ITEM", category: "PHARMACY" },
    { name: "Magimide", price: 0.83, type: "PHARMACY_ITEM", category: "PHARMACY" },
    { name: "Nalline / Lethidrone", price: 0.83, type: "PHARMACY_ITEM", category: "PHARMACY" },
    { name: "Procaine", price: 0.83, type: "PHARMACY_ITEM", category: "PHARMACY" },
    { name: "Regonal", price: 0.1, type: "PHARMACY_ITEM", category: "PHARMACY" },
    { name: "Rebiunal / Robinul", price: 0.83, type: "PHARMACY_ITEM", category: "PHARMACY" },
    { name: "Vasoxyl", price: 3.12, type: "PHARMACY_ITEM", category: "PHARMACY" },
    { name: "Wyamine", price: 0.83, type: "PHARMACY_ITEM", category: "PHARMACY" },
    { name: "Tubocurarine Chloride Inj", price: 8.96, type: "Injection", category: "PHARMACY" },
    { name: "Thiopentone Sod Inj 500mg", price: 72.0, type: "Injection", category: "PHARMACY" },
    { name: "Succinylcholin Inj 500mg", price: 220.0, type: "Injection", category: "PHARMACY" },
    { name: "Propofol Inj Per mg", price: 1.5, type: "Injection", category: "PHARMACY" },
    { name: "Fentanyl Inj 0.5cc", price: 60.0, type: "Injection", category: "PHARMACY" },
    { name: "Sodalime", price: 15.0, type: "PHARMACY_ITEM", category: "PHARMACY" },
    { name: "Equipment Use", price: 12.0, type: "PHARMACY_ITEM", category: "PHARMACY" },
    { name: "General Anesthesia Usage Charge", price: 7.0, type: "PHARMACY_ITEM", category: "PHARMACY" },
];
