import { InventoryItem } from '../types';

export const PROCEDURES_REGISTRY: Partial<InventoryItem>[] = [
  // TECH FEES & LATE FEES
  { name: "Senior Medic OR Tech Fee (Simple/Inter)", price: 110.0, type: "Service", category: "PROCEDURES" },
  { name: "OR Suture Complex Tech Fee", price: 190.0, type: "Service", category: "PROCEDURES" },
  { name: "Late Fee (6pm-7am & Off Day)", price: 310.0, type: "Service", category: "PROCEDURES" },
  { name: "SEDATION MONITORING FEE", price: 1330.0, type: "Service", category: "PROCEDURES" },

  // EQUIPMENT USE CHARGES
  { name: "Nebulizer with Ipratropium", price: 120.0, type: "Service", category: "PROCEDURES" },
  { name: "Nebulizer with Epinephrine/Salbutamol", price: 180.0, type: "Service", category: "PROCEDURES" },
  { name: "Isolation Respiratory", price: 290.0, type: "Service", category: "PROCEDURES" },
  { name: "Hep. B Isolation", price: 370.0, type: "Service", category: "PROCEDURES" },
  { name: "Hep. B Isolation Delivery and OR", price: 1150.0, type: "Service", category: "PROCEDURES" },
  { name: "Full Contact Isolation", price: 550.0, type: "Service", category: "PROCEDURES" },
  { name: "Chest Suction (Per Day)", price: 470.0, type: "Service", category: "PROCEDURES" },
  { name: "Wall Suction (Per Day)", price: 470.0, type: "Service", category: "PROCEDURES" },
  { name: "Wound Vac. Machine (Per Day)", price: 470.0, type: "Service", category: "PROCEDURES" },
  { name: "Table Fan (Per Day)", price: 120.0, type: "Service", category: "PROCEDURES" },
  { name: "Monitor (Per Day)", price: 1250.0, type: "Service", category: "PROCEDURES" },
  { name: "Bilirubin Lights (Per Day)", price: 370.0, type: "Service", category: "PROCEDURES" },
  { name: "ET Tube use (Per Day)", price: 470.0, type: "Service", category: "PROCEDURES" },

  // PROCEDURES – SPECIAL STUDIES
  { name: "Enema", price: 240.0, type: "Procedure", category: "PROCEDURES" },
  { name: "LP Tray (Knee Aspiration)", price: 480.0, type: "Procedure", category: "PROCEDURES" },
  { name: "Thoracentesis", price: 1330.0, type: "Procedure", category: "PROCEDURES" },
  { name: "Parancentesis", price: 850.0, type: "Procedure", category: "PROCEDURES" },
  { name: "N.G Tube Insertion", price: 160.0, type: "Procedure", category: "PROCEDURES" },
  { name: "O.G Tube Insertion (Per Day)", price: 160.0, type: "Procedure", category: "PROCEDURES" },
  { name: "Douch", price: 120.0, type: "Procedure", category: "PROCEDURES" },
  { name: "I&D Small", price: 670.0, type: "Procedure", category: "PROCEDURES" },
  { name: "I&D Medium", price: 850.0, type: "Procedure", category: "PROCEDURES" },
  { name: "I&D Large", price: 1040.0, type: "Procedure", category: "PROCEDURES" },
  { name: "Rice Poisoning (Gastric Lavage)", price: 1320.0, type: "Procedure", category: "PROCEDURES" },
  { name: "Epidural Blood Patch", price: 1470.0, type: "Procedure", category: "PROCEDURES" },
  { name: "Dilateria Placement", price: 300.0, type: "Procedure", category: "PROCEDURES" },
  { name: "Suture Small (1-2)", price: 1030.0, type: "Procedure", category: "PROCEDURES" },
  { name: "Suture Medium (3-9)", price: 1600.0, type: "Procedure", category: "PROCEDURES" },
  { name: "Suture Large (10+)", price: 550.0, type: "Procedure", category: "PROCEDURES" },
  { name: "Dorsal Slit for Phimosis", price: 670.0, type: "Procedure", category: "PROCEDURES" },
  { name: "Ear Irrigation", price: 150.0, type: "Procedure", category: "PROCEDURES" },
  { name: "Dilatation of Urethra", price: 830.0, type: "Procedure", category: "PROCEDURES" },
  { name: "Urethral Filiforms", price: 850.0, type: "Procedure", category: "PROCEDURES" },
  { name: "Chest Tube Insertion (Out of OR)", price: 3100.0, type: "Procedure", category: "PROCEDURES" },
  { name: "Central Venous Line Insertion", price: 4350.0, type: "Procedure", category: "PROCEDURES" },
  { name: "E.T Tube Insertion", price: 800.0, type: "Procedure", category: "PROCEDURES" },
  { name: "E.T Tube Care (Per Day)", price: 400.0, type: "Procedure", category: "PROCEDURES" },
  { name: "E.T Tube (Taken by Patient)", price: 160.0, type: "Procedure", category: "PROCEDURES" },
  { name: "Ambu Bag", price: 770.0, type: "Procedure", category: "PROCEDURES" },
  { name: "Ambu Bag Use (Per Day)", price: 240.0, type: "Procedure", category: "PROCEDURES" },
  { name: "Ambu Bag (Taken by Patient)", price: 560.0, type: "Procedure", category: "PROCEDURES" },
  { name: "CPAP Daily", price: 430.0, type: "Procedure", category: "PROCEDURES" },
  { name: "Trach Care", price: 550.0, type: "Procedure", category: "PROCEDURES" },
  { name: "Cut Down", price: 1220.0, type: "Procedure", category: "PROCEDURES" },
  { name: "Hyfrecation", price: 400.0, type: "Procedure", category: "PROCEDURES" },
  { name: "Suprapubic (SP) Catheter Insertion", price: 1250.0, type: "Procedure", category: "PROCEDURES" },
  { name: "Acupuncture / Stun Gun", price: 170.0, type: "Procedure", category: "PROCEDURES" },
  { name: "Debridement Small", price: 540.0, type: "Procedure", category: "PROCEDURES" },
  { name: "Debridement Medium", price: 770.0, type: "Procedure", category: "PROCEDURES" },
  { name: "Debridement Large", price: 1220.0, type: "Procedure", category: "PROCEDURES" },
  { name: "Suture / Clip / Drain Removal", price: 120.0, type: "Procedure", category: "PROCEDURES" },
  { name: "Decubitus Care Small", price: 50.0, type: "Procedure", category: "PROCEDURES" },
  { name: "Decubitus Care Medium", price: 100.0, type: "Procedure", category: "PROCEDURES" },
  { name: "Decubitus Care Large", price: 100.0, type: "Procedure", category: "PROCEDURES" },
  { name: "Wound/Cath Irrigation", price: 120.0, type: "Procedure", category: "PROCEDURES" },
  { name: "OB Emergency Pack Use", price: 120.0, type: "Procedure", category: "PROCEDURES" },
  { name: "Infant Resuscitation", price: 770.0, type: "Procedure", category: "PROCEDURES" },
  { name: "Wound Vac Daily Charge", price: 470.0, type: "Procedure", category: "PROCEDURES" },
  { name: "Wound Vac Change (No Anesthesia)", price: 1400.0, type: "Procedure", category: "PROCEDURES" },
  { name: "Wound Vac Change (With Ketamine)", price: 3000.0, type: "Procedure", category: "PROCEDURES" },
  { name: "Wound Vac Change (In OR)", price: 9300.0, type: "Procedure", category: "PROCEDURES" },
  { name: "Plaster Removal Charge", price: 200.0, type: "Procedure", category: "PROCEDURES" },
  { name: "Tongue Release (Frenulectomy)", price: 3410.0, type: "Procedure", category: "PROCEDURES" },
  
  // DRESSINGS
  { name: "Gentian Violet Small", price: 40.0, type: "Service", category: "PROCEDURES" },
  { name: "Gentian Violet Medium", price: 50.0, type: "Service", category: "PROCEDURES" },
  { name: "Gentian Violet Large", price: 80.0, type: "Service", category: "PROCEDURES" },
  { name: "Gentian Violet Vaginal", price: 80.0, type: "Service", category: "PROCEDURES" },
  { name: "Wet Dressings Small", price: 120.0, type: "Service", category: "PROCEDURES" },
  { name: "Wet Dressings Medium", price: 240.0, type: "Service", category: "PROCEDURES" },
  { name: "Wet Dressings Large", price: 470.0, type: "Service", category: "PROCEDURES" },
  { name: "Dressing Small", price: 100.0, type: "Service", category: "PROCEDURES" },
  { name: "Dressing Medium", price: 180.0, type: "Service", category: "PROCEDURES" },
  { name: "Dressing Large", price: 400.0, type: "Service", category: "PROCEDURES" },
  { name: "Dressing Large Burn", price: 950.0, type: "Service", category: "PROCEDURES" },
  { name: "Wound – Vac Dressing Small", price: 930.0, type: "Service", category: "PROCEDURES" },
  { name: "Wound – Vac Dressing Medium", price: 1440.0, type: "Service", category: "PROCEDURES" },
  { name: "Wound – Vac Dressing Large", price: 2000.0, type: "Service", category: "PROCEDURES" },
  { name: "Central Line Dressing Change", price: 300.0, type: "Service", category: "PROCEDURES" },

  // STUDIES
  { name: "Lower Extremity Segmental Doppler (ABI)", price: 770.0, type: "Study", category: "PROCEDURES" },
  { name: "Joint Manipulation (Outpatient)", price: 3620.0, type: "Procedure", category: "PROCEDURES" },
  { name: "Lumbar Puncture / Spinal Tap", price: 1250.0, type: "Procedure", category: "PROCEDURES" },
  { name: "Axillary Block", price: 1250.0, type: "Procedure", category: "PROCEDURES" },
  { name: "Supra - Cavicullar Block", price: 2340.0, type: "Procedure", category: "PROCEDURES" },
  { name: "Intra - Costal Rib Block", price: 770.0, type: "Procedure", category: "PROCEDURES" },
  { name: "Lower Extremity Venus Duplex Study", price: 1800.0, type: "Study", category: "PROCEDURES" },
  { name: "Carotid Duplex Study", price: 1800.0, type: "Study", category: "PROCEDURES" },
  { name: "EKG", price: 500.0, type: "Study", category: "PROCEDURES" },
  { name: "Foley Cath Insertion (3 way)", price: 700.0, type: "Procedure", category: "PROCEDURES" },
  { name: "Foley Cath Insertion (2 way)", price: 400.0, type: "Procedure", category: "PROCEDURES" },
  { name: "Cath Insertion", price: 300.0, type: "Procedure", category: "PROCEDURES" },
  { name: "Ultrasound by Physician", price: 1440.0, type: "Study", category: "PROCEDURES" },
  { name: "Ultrasound FAST", price: 500.0, type: "Study", category: "PROCEDURES" },
  { name: "Tru Cut/ Thu Cut", price: 3800.0, type: "Procedure", category: "PROCEDURES" },

  // DISPOSABLES
  { name: "Disposal Syringe (Insulin/1cc)", price: 20.0, type: "Supply", category: "PROCEDURES" },
  { name: "Disposal Syringe (3ml/5ml)", price: 10.0, type: "Supply", category: "PROCEDURES" },
  { name: "Disposal Syringe (10ml/20ml)", price: 30.0, type: "Supply", category: "PROCEDURES" },
  { name: "Disposal Syringe (30ml/50ml)", price: 40.0, type: "Supply", category: "PROCEDURES" },
  { name: "Sterile Suction Tray", price: 270.0, type: "Supply", category: "PROCEDURES" },
  { name: "Latex Gloves", price: 10.0, type: "Supply", category: "PROCEDURES" },
  { name: "Surgical Blade", price: 10.0, type: "Supply", category: "PROCEDURES" }
];