import { InventoryItem } from '../types';

export const SURGERY_OR_REGISTRY: Partial<InventoryItem>[] = [
    { name: "Critical Care Monitoring or Ward", price: 9320.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "OR Room Charges", price: 450.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Abdomino-Perineal Resection (APR)", price: 35500.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Adrenalectomy", price: 23000.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Appendectomy", price: 17500.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Lap Coly + TAH", price: 39500.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Lap Chole + Hernioraphy", price: 33500.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Appendectomy, Laparoscopic", price: 26500.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Cholecystectomy (Laparoscopic or Open)", price: 26500.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Cholecystectomy + Common Bile Duct Expl. (CBDE)", price: 33000.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Cholecystectomy + CODE + Sphincteroplasty", price: 35500.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Cholecystectomy", price: 19500.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Colectomy—Partial", price: 30500.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Colectomy—Total", price: 38500.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Colostomy", price: 19500.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Colostomy Closure", price: 23000.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Enterostomy, all types", price: 19500.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Exploratory Laparotomy—Minor", price: 15500.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Exploratory Laparotomy—Major", price: 23000.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Pyloroplasty (With or without vagotomy)", price: 23000.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Gastro-Jejunostomy/Duodenostomy (Bilroth I or II)", price: 26500.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Gastrectomy (Partial)", price: 26500.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Gastrectomy (Total)", price: 30500.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Gastrostomy/Jejunostomy", price: 10000.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Herniorraphy, Incisional/Ventral Orchectomy/Epigastric", price: 17500.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Herniorraphy, Incisional/Ventral with Mesh", price: 21500.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Herniorraphy, Inguinal (Unilateral) IH Repair", price: 14000.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Herniorraphy, Inguinal (Bilateral)", price: 19500.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Herniorraphy, Umbilical", price: 14000.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Hydrocelectomy", price: 14000.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Pancreatectomy", price: 33000.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Intussusception", price: 15500.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Pancreatic Pseudocyst", price: 30600.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Perforation, closure of", price: 17500.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Pyloromyotomy", price: 19500.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Resection small bowel", price: 19500.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Resection Abdominal Wall", price: 15200.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Spleno-Renal or Portocaval Decompression", price: 30600.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Splenectomy", price: 26500.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Colonic Volvulus", price: 15500.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Laparoscopic Heller Myotomy", price: 30600.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Bronchoscopy & Endoscopic RXN of Obstruction Tumor", price: 18000.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "PSARP", price: 46000.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Laparoscopic Nissen Fundoplication", price: 30600.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Hemorrhoidectomy", price: 12000.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Repair of Ano-Rectal Malformation (e.g Pena)", price: 30600.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Rectal Fistulotomy", price: 12000.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Repair of Rectal Prolapse", price: 26500.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Repair Dilation", price: 7500.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Rectal Polypectomy", price: 3000.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Laparoscopic Endorectal Pull through", price: 46000.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "EUA", price: 1330.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Anoplasty Revision", price: 8000.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Needle Biopsy – OR", price: 2700.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Needle Biopsy – Outpatient", price: 1500.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Cervical Biopsy", price: 8000.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "L.N Biopsy", price: 6500.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Modified Radical Mastectomy", price: 26500.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Simple Mastectomy", price: 15500.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Biopsy/Removal of Cyst or Mass", price: 7700.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Segmentectomy", price: 15400.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Exc. of Breast Mass", price: 15400.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Video EGD", price: 3000.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Video Colonoscopy", price: 4500.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Video Sigmoidoscopy", price: 3000.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Proctoscopy (rigid)", price: 2000.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Laryngoscopy, Retrieval of Foreign Body", price: 3000.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Esophageal Dilatation (Hydrostatic or Rigid)", price: 5700.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Video Bronchoscopy", price: 4500.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Video Mediastinoscopy", price: 18000.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Rectal Polypectomy with video colonoscopy", price: 9500.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Diagnostic Laparoscopy", price: 10500.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Triple Endoscopy", price: 11000.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Choledoshoscopy", price: 8800.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Prostatectomy: TURP/TUVP", price: 23500.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Prostatectomy: Suprapubic", price: 23500.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "TURBT", price: 23500.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Pyelolithotomy", price: 26500.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Nephrolithotomy (Boyce)", price: 33000.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Ureterolithotomy", price: 23500.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Cystostomy (Bladder Stone Removal)", price: 14000.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Cystectomy", price: 23000.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Bladder repair with other procedures", price: 7500.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Colposuspension", price: 5000.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Nephrectomy", price: 23500.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Hypospadius/Epispadius Repair", price: 15500.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Orchiopexy", price: 14500.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Removal of urethral stone", price: 11500.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Urethral dilatation", price: 4000.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Meatotomy", price: 3000.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Cystostomy", price: 7500.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Circumcision, Newborn", price: 3000.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Circumcision, Under 10 years", price: 3500.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Circumcision, over 10 years", price: 5000.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Amputation Penis/ Penectomy", price: 7500.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Urachal Cyst/Sinus", price: 11500.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Urethral Reconstruction", price: 19500.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Varicocelectomy", price: 11500.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Video Cystoscopy", price: 8800.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Video Cystoscopy with Retrograde Ureterograms", price: 12000.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Direct video internal urethrotomy (DVIU)", price: 13500.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Endometrial Ablation", price: 23500.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Pigtail u/s guided Tube Placement OR", price: 12500.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Pigtail u/s guided Tube Placement OPD", price: 5500.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Uteroscopy", price: 14500.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Penoplasty/Scrotoplasty", price: 19500.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Burr holes only", price: 10000.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Trauma", price: 30000.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Tumor", price: 40000.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Resection of Meningo – Myelocele", price: 26500.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Lumbar Laminectomy", price: 40000.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Anterior Cervical Discectomy & Fusion (ACD&F)", price: 40000.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Posterior Cervical Fusion", price: 40000.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "1-2 fingers only", price: 11500.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Hand or Foot", price: 23000.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Motor", price: 23000.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Dorsal Unilateral", price: 15500.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Lumbar unilateral", price: 15500.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Resection of Hemangio Sarcoma", price: 26000.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Neuroblastomy", price: 45000.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Vein TS Release", price: 18000.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Glossectomy (Hemi)", price: 23000.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Parotidectomy or Excision tumor", price: 19500.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Radical neck dissection unilateral", price: 23000.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Resection mandible or maxilla (Tumor)", price: 23000.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Thyroidectomy – Lobectomy", price: 23000.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Thyroidectomy – Total", price: 26500.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Thyro – Glossal Duct/Branchial Cleft Cyst", price: 15500.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Tracheostomy", price: 11500.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Mandible or maxilla ORIF with arch bars", price: 25000.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Zygomatic Fracture ORIF", price: 19500.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Trauma of Face or Neck - Minor", price: 10000.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Trauma of Face or Neck - Major", price: 15500.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "T&A (Pediatric or Adult)", price: 13500.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Nasal Polypectomy (Minor)", price: 6500.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Nasal Polypectomy (Major)", price: 11000.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Myringotomy without tubes", price: 4500.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Myringotomy with tubes", price: 10000.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Exision Cystic Hygroma", price: 19500.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Exision scalp cyst", price: 15500.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Exision Cyst", price: 14000.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Repair of Cleft Lip (Unilateral)", price: 19500.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Bilateral Cleft Lip", price: 23000.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Repair of Cleft Palate", price: 23000.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Repair Cleft Lip and Palate Together", price: 38500.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Rhinoplasty", price: 19500.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Burn Contr. Release – Minor", price: 11500.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Burn Contr. Release – Major", price: 19500.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Raise", price: 10000.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Delay", price: 10000.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Advance", price: 10000.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Plastic repair of wounds – Minor", price: 7500.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Plastic repair of wounds – Major", price: 19500.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Exc. of Tumor/Cyst/Mole of Skin – Minor", price: 6000.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Exc. of Tumor/Cyst/Mole of Skin – Major", price: 10000.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "I&D – Minor", price: 6000.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "I&D – Major", price: 13500.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Debridement – Minor", price: 3000.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Debridement – Major", price: 10000.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Escharotomy", price: 6000.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Skin Graft – Minor", price: 7500.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Skin Graft – Major", price: 17500.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Z - Plasty", price: 11500.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Secondary Closure", price: 6000.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Dressing change – Minor", price: 1600.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Dressing change – Major", price: 3700.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Fasciotomy", price: 7500.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Vomer Excision", price: 7500.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Resection Moss", price: 19200.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Leceration Repair", price: 13500.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Diaphramatic Hernia Repair", price: 33000.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Esophagectomy, all types", price: 44000.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Esophageal Dilation/Stent Placement", price: 17500.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Resection of Mediastinal Tumor", price: 33000.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Lobectomy/Pneumonectomy", price: 33000.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Thoracotomy, Exploratory (Trauma, etc.)", price: 26500.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Chest tube insertion (Tube Thoracostomy)", price: 6500.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Decortication", price: 33000.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Thoracoscopy", price: 33000.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Video Mediastinoscopy", price: 19700.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Mitral Valve Commisurotomy", price: 44000.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Cardioversion (in OR)", price: 11100.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "PEG (Percutaneous Endoscopic Gastrostomy)", price: 17500.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Pacemaker Placement Temporary", price: 12500.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Pacemaker Placement Permanent", price: 30000.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Cardioversion (Ward/OPD)", price: 5500.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Carotid Endarterectomy (CEA)", price: 40050.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Aortic Aneurysm Repair (AAR)", price: 46000.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Aorto – Bifemoral Bypass Graft", price: 46000.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Emboxlomy", price: 15500.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Fem – Pop Bypass", price: 30500.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Fem – Distal Bypass", price: 38500.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Varicose veins", price: 22000.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Repair of Vascular injury", price: 15500.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Greenfield Filter Placement", price: 30000.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Port – a – Cath/Hickman Cath Placement", price: 17500.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Resection of Congenital Venous Malformation (Minor)", price: 11000.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Resection of Congenital Venous Malformation (Major) (AVM)", price: 30500.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Chemoport Removal", price: 8000.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Lap Repair/Hemaslasia/Diaphramatic/Hepotic Injury", price: 33030.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Chest wall tumor", price: 19200.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Excision of Mass", price: 15400.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Symphyseotomy", price: 2100.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Circlage", price: 3000.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Circlage Remove", price: 2500.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Cystocele Repair only", price: 9500.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Hysterectomy, Abdominal (TAH)", price: 24000.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Vag Hyst", price: 24000.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Rectocele Repair", price: 7800.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Hysterectomy for raptured uterus", price: 19000.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Salpingo – Oophorectomy (B.S.O)", price: 10000.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Ovarian Cyst Removal", price: 10000.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Tubal Ligation (BTL, BTF)", price: 7000.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Perineal Repair", price: 5700.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Radical Pelvic Exteneration", price: 30000.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "V-V Fistula Repair", price: 14100.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Vaginal or Cervical polypectomy", price: 3000.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Myomectomy", price: 11800.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Exc. Bartholin cyst Inpatient", price: 9200.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Exc. Bartholin cyst Outpatient", price: 3400.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Diagnostic Laparoscopy", price: 10500.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Clitorectomy", price: 3000.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Vulvectomy", price: 11800.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Tubal Micro – Surgery", price: 30000.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Bladder/Vaginal Reconstruction", price: 20000.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Adhesiolysis", price: 5000.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "D&C", price: 2700.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "D&C (OPD)", price: 1500.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Placenta", price: 2700.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Spontaneous Cephalic Vag. mn,Delivery (Midwife)", price: 5500.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Vacuum Delivery by midwife", price: 7000.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Episiotomy Repair (without delivery)", price: 2000.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Episiotomy Repair (with delivery)", price: 500.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Physician Surcharge for any Delivery", price: 4200.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "All in OPD (no room charge)", price: 2000.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "C – Section", price: 15000.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "C – Section with raptured uterus  (but no hysterectomy)", price: 21000.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Outside Delivery", price: 3000.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "LaForte Colpocleisis", price: 9700.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Exam Under Anesthesia (EUA)", price: 1330.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Suburethral Sling (e.g. Tensor Fascia Lata)", price: 9000.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Destructive Delivery", price: 11000.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Laparoscopic ovarian cystectomy", price: 16000.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Laparoscopic BTL", price: 12100.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Hysteroscopy", price: 10500.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Laparoscopic TAH", price: 26500.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Vaginal Tear Repair", price: 3000.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Vaginal Tear Repair (by physician)", price: 12000.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Vaginal wall Laceration repair", price: 5800.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Omentectomy", price: 11800.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Resection Endometrial Cyst", price: 24200.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Hymenotomy", price: 5000.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Forequarter", price: 31800.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Shoulder Disarticulation", price: 31800.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Arm through humerus (above elbow)", price: 21000.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Forearm through radius & ulna or wrist or hand", price: 21000.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Fingers 1-5", price: 15600.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Hindquarter", price: 31800.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Hip disarticulation", price: 31800.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Knee disarticulation", price: 26400.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "AK through femur or knee", price: 26400.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "BK through tibia & fibula or ankle", price: 26400.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Foot, metatarsal", price: 18600.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Metatarsal with toe", price: 18600.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Toe metatarsophalangeal joint", price: 18600.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Toe", price: 10200.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Stump Revision", price: 15000.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Spine cervical posterior", price: 42000.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Special Spine cervical atlas – axis or cervico – cranial", price: 42000.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Spine lumbar or thoracic", price: 42000.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Special spine scoliosis", price: 42000.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Shoulder", price: 42000.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Proximal tibia (Bilateral + 50%)", price: 28800.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Tibia", price: 24000.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Shoulder", price: 27600.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Shoulder capsulorrhaphy for recurrent dislocation", price: 27600.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Elbow", price: 26400.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Wrist", price: 26400.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Fingers 1-5", price: 14400.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Hip", price: 31800.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Knee", price: 27600.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Knee Biopsy only", price: 7800.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Ankle", price: 10800.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Humerus", price: 30000.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Radius and Ulna", price: 30000.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Proximal Femur", price: 30000.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Femur shaft", price: 30000.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Tibia with iliac graft", price: 30000.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Tibia with sliding graft", price: 36000.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Hip", price: 4200.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Knee", price: 4200.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Shoulder", price: 3600.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Shoulder", price: 30000.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Elbow", price: 24000.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Acromioclavicular", price: 24000.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Hip", price: 36000.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Hip with acetabular fracture fixation", price: 45000.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Finger 1-5", price: 10200.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Distal clavicle", price: 18000.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Acromion", price: 18000.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Coccyx", price: 18000.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Distal Ulna", price: 18000.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Radial Head", price: 18000.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Fibulectomy", price: 18000.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Humerus", price: 27000.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Femur", price: 27000.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Tibia or Fibula", price: 27000.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Foot", price: 27000.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Pin Traction", price: 2200.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Tibia and Fibula", price: 4200.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Elbow", price: 3600.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Humerus Shaft", price: 1500.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Humerus (supracondylar, epicondylar, transcondylar)", price: 2200.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Monteggia fracture", price: 2700.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Radial head or neck", price: 2200.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Ulnar olecranon process", price: 1500.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Radial Shaft", price: 4200.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Ulnar shaft", price: 4200.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Distal Radius (colles or smith type) Wrist", price: 3600.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Shoulder", price: 3600.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Carpal Bone", price: 1500.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Metacarpal Single", price: 2200.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Metacarpal Multiple", price: 3600.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Bennet Fracture", price: 2200.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Bennet Fracture with skeletal fix", price: 2900.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Phalanges shaft proximal or middle 1-2", price: 2900.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Phalanges shaft proximal or middle 3-5", price: 4200.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Articular fracture MP or PIP joint 1-5", price: 2900.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Hip", price: 4200.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Femur shaft", price: 2900.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Tibia", price: 2900.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Knee", price: 4200.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Bimalleolar", price: 2900.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Trimalleolar", price: 3300.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Wrist", price: 3600.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Os Calcis", price: 2200.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Metatarsals 1-2", price: 1500.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Metatarsals 3-5", price: 2900.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Great Toe", price: 2200.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Closed Reduction + External Fixator", price: 22800.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Closed Reduction with Pins & Plaster", price: 10200.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Foot", price: 2900.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Radial & Ulna", price: 31200.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Knee", price: 16800.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Iliac Ex", price: 16800.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Hip", price: 43800.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Humerus shaft and Supracondylar Elbow T-fracture", price: 32400.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Humerus greater tuberosity", price: 27000.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Hemerus epicondylar fracture, capitelum", price: 21600.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Humerus condylar fracture", price: 21600.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Elbow comminuted", price: 32400.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Monteggia fracture", price: 28200.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Radial Head", price: 21600.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Ulnar shaft", price: 19200.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Olecranon process", price: 19200.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Radial shaft", price: 19200.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Colles fracture", price: 19200.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Metacarpal Single/Multiple", price: 13200.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Bennet fracture of the thumb", price: 15600.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Fingers 1-5", price: 15600.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Finger articular fractures 1-5", price: 19200.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Acetabulum", price: 36000.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Femur Neck or intertrochanteric or prosthesis", price: 36000.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Femur through shaft or supracondylar", price: 31200.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Patella", price: 24000.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Tibial Plateau", price: 31200.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Tibial Shaft", price: 31200.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Tibial, medical malleolous", price: 22800.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Fibular lateral malleolous", price: 19200.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Both bone forearm", price: 27000.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Open reduction of rami", price: 25200.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Tibia and Fibula", price: 41400.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Open reduction with external fixation", price: 24000.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Bimalleolar, Ankle", price: 27000.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Trimalleolar", price: 36000.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "OS Calcis (calcanius) or talus", price: 25200.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Metatarsals 1-5", price: 16200.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "CRIF Clavicle", price: 24000.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Pelvic", price: 31700.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Navicular", price: 25200.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Radial & Ulna", price: 35400.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Knee", price: 18600.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Iliac Ex", price: 18600.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Hip", price: 49200.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Humerus shaft and Supracondylar Elbow T-fracture", price: 37200.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Humerus greater tuberosity", price: 30000.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Hemerus epicondylar fracture, capitelum", price: 24000.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Humerus condylar fracture", price: 24000.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Elbow comminuted", price: 37200.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Monteggia fracture", price: 32400.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Radial Head", price: 24000.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Ulnar shaft", price: 21600.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Olecranon process", price: 21600.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Radial shaft", price: 21600.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Colles fracture", price: 21600.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Metacarpal Single/Multiple", price: 15600.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Bennet fracture of the thumb", price: 18000.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Fingers 1-5", price: 18000.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Finger articular fractures 1-5", price: 21600.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Acetabulum", price: 40800.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Femur Neck or intertrochanteric or prosthesis", price: 40800.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Femur through shaft or supracondylar", price: 36000.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Patella", price: 26400.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Tibial Plateau", price: 36000.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Tibial Shaft", price: 36000.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Tibial, medical malleolous", price: 25200.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Fibular lateral malleolous", price: 22200.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Both bone forearm", price: 30600.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Open reduction of rami", price: 28200.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Tibia and Fibula", price: 46300.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Open reduction with external fixation", price: 27600.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Bimalleolar, Ankle", price: 30600.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Trimalleolar", price: 40800.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "OS Calcis (calcanius) or talus", price: 28800.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Metatarsals 1-5", price: 18000.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "ORIF Clavicle", price: 27000.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Spine", price: 31800.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Humerus", price: 22200.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Radius", price: 25200.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Ulna", price: 25200.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Pelvis", price: 31800.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Pelvis with open reduction dislocation", price: 38400.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Proximal femur", price: 28200.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Femur shaft", price: 28200.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Humerus proximal/distal", price: 24000.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Olecranon", price: 13800.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Radius", price: 21600.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Ulna", price: 21600.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Wrist & hand", price: 21600.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Femur", price: 27000.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Elbow", price: 27000.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Wrist with sliding graft", price: 21600.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Wrist with distal bone graft", price: 21600.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Carpo – Metacarpal joint thumb", price: 21600.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Carpo – Metacarpal joint fingers", price: 21600.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Thumb fusion in opposition with graft", price: 21600.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Metacarpal – phalangeal joint", price: 13800.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Interphalangeal joint", price: 13800.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Hip", price: 32400.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Knee", price: 32400.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Triple", price: 24000.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Grice procedure", price: 18000.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Tendon repairs in hand Flexor 1-5", price: 19200.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Flexor secondary with graft 1-2/3-5", price: 24600.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Extensor 1-2/3-5", price: 19200.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Extensor secondary with graft 1-5", price: 24600.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Multiple Z Plasty & Excision of scar in knee", price: 24000.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Fascial Release of Knee", price: 24000.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Achilles tendon repair", price: 16200.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Achilles tendon repair secondary with graft", price: 19200.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Resection of Morton’s Neuroma", price: 10800.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Clubfoot medial release", price: 17400.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Bunionectomy (Metchel)", price: 19200.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Syndactyle", price: 19200.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Obturator Neurectomy Extra pelvic", price: 10800.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Hanging Hip", price: 24000.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Girdlestone hip resection", price: 24000.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Achilles tendon lengthening (TAL)", price: 11200.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Achilles tendon lengthening (TAL), Bilateral", price: 19200.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Secondary repair knee collartersal of cruciate lig", price: 32400.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Houser procedure for recurrent/dislocated patella", price: 28200.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Carpal Tunnel Release", price: 13800.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Tendon Sheath release for Dequervain’s syndrome", price: 16200.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Resection Elbow", price: 24000.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Steindler flexorplasty Elbow", price: 32400.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Ganglion Wrist", price: 10800.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Tendon transfer wrist", price: 24000.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Flexor Slide forearm", price: 21600.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Palmar fasciectomy for Dupuytren’s contracture", price: 21600.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "EVA", price: 1330.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Knee Meniscectomy", price: 21600.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Baker’s Cyst", price: 16200.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Patellectomy", price: 16200.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Muscle Biopsy", price: 9600.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Middle bone biopsy superficial/deep", price: 9600.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Bone biopsy by incision superficial/deep", price: 9600.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "I & D Hip", price: 16200.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Fascial Arthroplasty of Elbow", price: 43800.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Remove Hardware Outpatient", price: 10800.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Remove Hardware (Major) Inpatient", price: 15600.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Remove Hardware (Complex) Inpatient", price: 30000.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Finger Release (Simple)", price: 7200.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Finger Release (Major)", price: 13800.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Hand Reconstruction", price: 27000.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
    { name: "Hip Aspiration", price: 13500.0, type: "Surgery", category: "SURGERY, O.R. & DELIVERY" },
];