import { InventoryItem } from '../types';

export const XRAY_REGISTRY: Partial<InventoryItem>[] = [
    { id: 5000, name: "Digital X-Ray (Single View)", price: 350.0, type: "Digital", category: "X-RAY" },
    { id: 5001, name: "Chest X-Ray (AP & LAT)", price: 700.0, type: "Digital", category: "X-RAY" },
    { id: 5002, name: "Barium Contrast Study", price: 2200.0, type: "Study", category: "X-RAY" },
    { id: 5003, name: "Ankle Digital: AP (Mortice) and LAT", price: 350.0, type: "Service", category: "X-RAY" },
    { id: 5004, name: "Ankle Digital: Oblique", price: 350.0, type: "Service", category: "X-RAY" },
    { id: 5005, name: "Ankle Digital: Strain Film", price: 350.0, type: "Service", category: "X-RAY" },
    { id: 5006, name: "Calcaneus/Heel (OS Calcis) Digital: LAT & AXIAL", price: 350.0, type: "Service", category: "X-RAY" },
    { id: 5007, name: "Cervical Spine Digital: AP", price: 350.0, type: "Service", category: "X-RAY" },
    { id: 5008, name: "Cervical Spine Digital: LAT", price: 350.0, type: "Service", category: "X-RAY" },
    { id: 5009, name: "Cervical Spine Digital: R&L Oblique", price: 350.0, type: "Service", category: "X-RAY" },
    { id: 5010, name: "Cervical Spine Digital: Open Mouth Odontoid", price: 350.0, type: "Service", category: "X-RAY" },
    { id: 5011, name: "Cervical Spine Digital: Flexion & Extension", price: 350.0, type: "Service", category: "X-RAY" },
    { id: 5012, name: "Cervicothoracic Digital: Oblique", price: 350.0, type: "Service", category: "X-RAY" },
    { id: 5013, name: "Chest Digital: PA OR AP", price: 350.0, type: "Service", category: "X-RAY" },
    { id: 5014, name: "Chest Digital: PA OR AP Extra Large", price: 700.0, type: "Service", category: "X-RAY" },
    { id: 5015, name: "Chest Digital: LAT", price: 350.0, type: "Service", category: "X-RAY" },
    { id: 5016, name: "Chest Digital: Oblique", price: 350.0, type: "Service", category: "X-RAY" },
    { id: 5017, name: "Chest Digital: Apical Lordotic", price: 350.0, type: "Service", category: "X-RAY" },
    { id: 5018, name: "Clavicle Digital: PA", price: 350.0, type: "Service", category: "X-RAY" },
    { id: 5019, name: "Clavicle Digital: AP", price: 350.0, type: "Service", category: "X-RAY" },
    { id: 5020, name: "Elbow Digital: AP & LAT", price: 350.0, type: "Service", category: "X-RAY" },
    { id: 5021, name: "Elbow Digital: Tangential", price: 350.0, type: "Service", category: "X-RAY" },
    { id: 5022, name: "Elbow Digital: Other View", price: 350.0, type: "Service", category: "X-RAY" },
    { id: 5023, name: "Femur Digital: AP & LAT", price: 700.0, type: "Service", category: "X-RAY" },
    { id: 5024, name: "Femur Digital: R&L Oblique", price: 350.0, type: "Service", category: "X-RAY" },
    { id: 5025, name: "Foot Digital: AP & LAT", price: 350.0, type: "Service", category: "X-RAY" },
    { id: 5026, name: "Foot Digital: Oblique", price: 350.0, type: "Service", category: "X-RAY" },
    { id: 5027, name: "Foot Digital: Special Views", price: 350.0, type: "Service", category: "X-RAY" },
    { id: 5028, name: "Forearm Digital: AP & LAT", price: 350.0, type: "Service", category: "X-RAY" },
    { id: 5029, name: "Forearm Digital: R&L Oblique", price: 350.0, type: "Service", category: "X-RAY" },
    { id: 5030, name: "Hand Digital: PA & Oblique", price: 350.0, type: "Service", category: "X-RAY" },
    { id: 5031, name: "Hand Digital: LAT", price: 350.0, type: "Service", category: "X-RAY" },
    { id: 5032, name: "Hand Digital: Extra View", price: 350.0, type: "Service", category: "X-RAY" },
    { id: 5033, name: "Hip Digital: AP Both Hips", price: 350.0, type: "Service", category: "X-RAY" },
    { id: 5034, name: "Hip Digital: AP One Hip", price: 350.0, type: "Service", category: "X-RAY" },
    { id: 5035, name: "Hip Digital: Cross Table LAT", price: 350.0, type: "Service", category: "X-RAY" },
    { id: 5036, name: "Hip Digital: Frog Leg LAT", price: 350.0, type: "Service", category: "X-RAY" },
    { id: 5037, name: "Hip Digital: Both Hips", price: 350.0, type: "Service", category: "X-RAY" },
    { id: 5038, name: "Hip Digital: One Hip", price: 350.0, type: "Service", category: "X-RAY" },
    { id: 5039, name: "Hip Digital: Abduction AP", price: 350.0, type: "Service", category: "X-RAY" },
    { id: 5040, name: "Hip Digital: Push-Pull", price: 700.0, type: "Service", category: "X-RAY" },
    { id: 5041, name: "Hip Digital: Arthrogram", price: 700.0, type: "Service", category: "X-RAY" },
    { id: 5042, name: "Humerus Digital: AP & LAT", price: 350.0, type: "Service", category: "X-RAY" },
    { id: 5043, name: "Humerus Digital: Transthoracic LAT", price: 350.0, type: "Service", category: "X-RAY" },
    { id: 5044, name: "Knee Digital: AP & LAT", price: 350.0, type: "Service", category: "X-RAY" },
    { id: 5045, name: "Knee Digital: R&L Oblique", price: 350.0, type: "Service", category: "X-RAY" },
    { id: 5046, name: "Knee Digital: Sunset View", price: 350.0, type: "Service", category: "X-RAY" },
    { id: 5047, name: "Knee Digital: Medial", price: 350.0, type: "Service", category: "X-RAY" },
    { id: 5048, name: "Knee Digital: Lateral", price: 350.0, type: "Service", category: "X-RAY" },
    { id: 5049, name: "Leg (Tibia/Fibula) Digital: AP & LAT", price: 700.0, type: "Service", category: "X-RAY" },
    { id: 5050, name: "Leg (Tibia/Fibula) Digital: R&L Oblique", price: 350.0, type: "Service", category: "X-RAY" },
    { id: 5051, name: "Lumber Spine Digital: AP", price: 350.0, type: "Service", category: "X-RAY" },
    { id: 5052, name: "Lumber Spine Digital: LAT", price: 350.0, type: "Service", category: "X-RAY" },
    { id: 5053, name: "Lumber Spine Digital: R&L Oblique", price: 700.0, type: "Service", category: "X-RAY" },
    { id: 5054, name: "Lumber Spine Digital: Spot Lateral", price: 350.0, type: "Service", category: "X-RAY" },
    { id: 5055, name: "Mandible Digital: Each View", price: 350.0, type: "Service", category: "X-RAY" },
    { id: 5056, name: "Pelvis Digital: AP", price: 350.0, type: "Service", category: "X-RAY" },
    { id: 5057, name: "Pelvis Digital: Joints", price: 700.0, type: "Service", category: "X-RAY" },
    { id: 5058, name: "Ribs Digital: AP (Full Chest)", price: 350.0, type: "Service", category: "X-RAY" },
    { id: 5059, name: "Ribs Digital: AP One Side", price: 350.0, type: "Service", category: "X-RAY" },
    { id: 5060, name: "Ribs Digital: Oblique", price: 350.0, type: "Service", category: "X-RAY" },
    { id: 5061, name: "Sacrum Digital: AP", price: 350.0, type: "Service", category: "X-RAY" },
    { id: 5062, name: "Sacrum Digital: LAT", price: 350.0, type: "Service", category: "X-RAY" },
    { id: 5063, name: "Sacrum Digital: Oblique", price: 350.0, type: "Service", category: "X-RAY" },
    { id: 5064, name: "Scapula Digital: AP", price: 350.0, type: "Service", category: "X-RAY" },
    { id: 5065, name: "Scapula Digital: LAT", price: 350.0, type: "Service", category: "X-RAY" },
    { id: 5066, name: "Shoulder Digital: AP Internal Rotation", price: 350.0, type: "Service", category: "X-RAY" },
    { id: 5067, name: "Shoulder Digital: AP External Rotation", price: 350.0, type: "Service", category: "X-RAY" },
    { id: 5068, name: "Shoulder Digital: Axillary & AP", price: 350.0, type: "Service", category: "X-RAY" },
    { id: 5069, name: "Shoulder Digital: Special Views", price: 350.0, type: "Service", category: "X-RAY" },
    { id: 5070, name: "Skull Digital: AP", price: 350.0, type: "Service", category: "X-RAY" },
    { id: 5071, name: "Skull Digital: LAT", price: 350.0, type: "Service", category: "X-RAY" },
    { id: 5072, name: "Skull Digital: Other Views", price: 350.0, type: "Service", category: "X-RAY" },
    { id: 5073, name: "Sternoclavicular J PA", price: 350.0, type: "Service", category: "X-RAY" },
    { id: 5074, name: "Sternoclavicular J \"Digital: KUB Abdomen, Abdo M\"", price: 350.0, type: "Service", category: "X-RAY" },
    { id: 5075, name: "Sternum Digital: Oblique", price: 350.0, type: "Service", category: "X-RAY" },
    { id: 5076, name: "Sternum Digital: LAT", price: 350.0, type: "Service", category: "X-RAY" },
    { id: 5077, name: "Temporo-Mandibula Digital: LAT", price: 350.0, type: "Service", category: "X-RAY" },
    { id: 5078, name: "Temporo-Mandibula Digital: AP", price: 350.0, type: "Service", category: "X-RAY" },
    { id: 5079, name: "Thoracic Spine Digital: AP", price: 350.0, type: "Service", category: "X-RAY" },
    { id: 5080, name: "Thoracic Spine Digital: LAT", price: 350.0, type: "Service", category: "X-RAY" },
    { id: 5081, name: "Thoracic Spine Digital: R or L Oblique Upper Th", price: 350.0, type: "Service", category: "X-RAY" },
    { id: 5082, name: "Thumb Digital: AP & LAT", price: 350.0, type: "Service", category: "X-RAY" },
    { id: 5083, name: "Wrist Digital: AP & LAT", price: 350.0, type: "Service", category: "X-RAY" },
    { id: 5084, name: "Wrist Digital: Scaphoid", price: 350.0, type: "Service", category: "X-RAY" },
    { id: 5085, name: "Wrist Digital: R&L Oblique", price: 350.0, type: "Service", category: "X-RAY" },
    { id: 5086, name: "Wrist Digital: Carpal Tunnel", price: 350.0, type: "Service", category: "X-RAY" },
    { id: 5087, name: "Zygomatic Arch Digital: Nose", price: 350.0, type: "Service", category: "X-RAY" },
    { id: 5088, name: "Zygomatic Arch Digital: Supero-Inferior", price: 350.0, type: "Service", category: "X-RAY" },
    { id: 5089, name: "Zygomatic Arch Digital: Lateral", price: 350.0, type: "Service", category: "X-RAY" },
    { id: 5090, name: "Xtra Large Film Digital:", price: 700.0, type: "Service", category: "X-RAY" },
    { id: 5091, name: "Contrast Studies Digital: Upper Gl", price: 1800.0, type: "Service", category: "X-RAY" },
    { id: 5092, name: "Contrast Studies Digital: Gallbladder (2 films)", price: 2500.0, type: "Service", category: "X-RAY" },
    { id: 5093, name: "Contrast Studies Digital: IV Cholagiogram ( 1 film)", price: 2500.0, type: "Service", category: "X-RAY" },
    { id: 5094, name: "Contrast Studies Digital: Barium Swallow", price: 1500.0, type: "Service", category: "X-RAY" },
    { id: 5095, name: "Contrast Studies Digital: Barium Enema (8 films)", price: 3500.0, type: "Service", category: "X-RAY" },
    { id: 5096, name: "Contrast Studies Digital: IVP Package < 40 kg", price: 4000.0, type: "Service", category: "X-RAY" },
    { id: 5097, name: "Contrast Studies Digital: IVP Package < 41 kg", price: 4500.0, type: "Service", category: "X-RAY" },
    { id: 5098, name: "Contrast Studies Digital: Retrograde Pyelogram Package", price: 3000.0, type: "Service", category: "X-RAY" },
    { id: 5099, name: "Contrast Studies Digital: Hysterosalpingogram 2 films", price: 3000.0, type: "Service", category: "X-RAY" },
    { id: 5100, name: "Contrast Studies Digital: Myelogram 6 films", price: 4000.0, type: "Service", category: "X-RAY" },
    { id: 5101, name: "X-Ray Late Charge After 5pm TK 70 Per film", price: 70.0, type: "Service", category: "X-RAY" },
    { id: 5102, name: "All films taken in O.R TK 70 additional Fee", price: 70.0, type: "Service", category: "X-RAY" },
    { id: 5103, name: "Basic film charge 8x10", price: 350.0, type: "Service", category: "X-RAY" },
    { id: 5104, name: "Basic film charge 10x14", price: 350.0, type: "Service", category: "X-RAY" },
    { id: 5105, name: "Basic film charge 14x17", price: 350.0, type: "Service", category: "X-RAY" }
  ];